import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tennis-go-'));
process.env.DB_PATH=path.join(dir,'test.sqlite');
const oldDb=new DatabaseSync(process.env.DB_PATH);
oldDb.exec('CREATE TABLE users(id TEXT PRIMARY KEY, name TEXT NOT NULL, username TEXT, tennis_rating INTEGER NOT NULL DEFAULT 1200, padel_rating INTEGER NOT NULL DEFAULT 1200, created_at TEXT NOT NULL)');
oldDb.prepare('INSERT INTO users(id,name,username,created_at) VALUES(?,?,?,?)').run('demo-legacy-0001','Старый игрок','','2026-09-01T00:00:00.000Z');
oldDb.exec('CREATE TABLE trainings(id TEXT PRIMARY KEY, coach_id TEXT NOT NULL REFERENCES users(id), format TEXT NOT NULL, seats INTEGER NOT NULL, court_id TEXT NOT NULL, starts_at TEXT NOT NULL, duration INTEGER NOT NULL, avg_ntrp REAL, price INTEGER NOT NULL, note TEXT NOT NULL, created_at TEXT NOT NULL)');
oldDb.prepare('INSERT INTO trainings VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('11111111-1111-4111-8111-111111111111','demo-legacy-0001','individual',1,'dinamo',new Date(Date.now()+86400000).toISOString(),60,3.5,1000,'Старая тренировка','2026-09-01T00:00:00.000Z');
oldDb.close();
const {server,db,verifyInitData}=await import('../server.mjs');
assert.equal(db.prepare('PRAGMA table_info(users)').all().some(column=>column.name==='ntrp_level'),true);
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
async function request(route,user,method='GET',body){const res=await fetch(base+'/api'+route,{method,headers:{'x-demo-user':user,'x-demo-name':encodeURIComponent(user==='demo-player-0001'?'Роман':'Вика'),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json()};}
const registration=(name,gender,role='player')=>({name,gender,role,playingYears:2,ntrpLevel:role==='coach'?null:3.5,about:role==='coach'?'Веду занятия по теннису':'Играю по выходным',coachYears:role==='coach'?1:null,avatarId:gender==='female'?'female-serve':'male-cap',photoData:null});
const coachPhoto='data:image/jpeg;base64,'+Buffer.from([0xff,0xd8,0xff,0xd9]).toString('base64');
test('game lifecycle and mutual confirmation preserve self selected NTRP',async()=>{
 assert.equal((await request('/me','demo-legacy-0001')).data.user.registered,0);
 assert.equal((await request('/me','demo-player-0001')).data.user.registered,0);
 assert.equal((await request('/games','demo-player-0001')).status,403);
 const pixel='data:image/jpeg;base64,'+Buffer.from([0xff,0xd8,0xff,0xd9]).toString('base64');
 const profile=await request('/profile','demo-player-0001','POST',{...registration('Роман Игрок','female'),city:'Анапа',phone:'+7 (999) 123-45-67',telegramContact:'@roman_tennis',photoData:pixel});
 assert.equal(profile.status,200);assert.equal(profile.data.user.name,'Роман Игрок');assert.equal(profile.data.user.ntrpLevel,3.5);assert.equal(profile.data.user.photoData,pixel);assert.equal(profile.data.user.registered,1);assert.equal(profile.data.user.city,'Анапа');assert.equal(profile.data.user.phone,'+7 (999) 123-45-67');assert.equal(profile.data.user.telegramContact,'roman_tennis');
 assert.equal((await request('/profile','demo-player-0001','POST',{...registration('Роман','female'),city:'Неизвестный город'})).status,400);
 assert.equal((await request('/profile','demo-player-0001','POST',{...registration('Роман','female'),phone:'123'})).status,400);
 assert.equal((await request('/profile','demo-player-0001','POST',{...registration('Роман','female'),telegramContact:'https://t.me/example'})).status,400);
 assert.equal((await request('/profile','demo-player-0001','POST',{...registration('','female'),ntrpLevel:8})).status,400);
 assert.equal((await request('/profile','demo-player-0002','POST',registration('Вика','female'))).status,200);
 assert.equal((await request('/profile','demo-player-0003','POST',registration('Игорь','male'))).status,200);
 const publicProfile=await request('/users/demo-player-0001','demo-player-0002');assert.equal(publicProfile.status,200);assert.equal(publicProfile.data.user.name,'Роман Игрок');assert.equal(publicProfile.data.user.ntrpLevel,3.5);assert.equal(publicProfile.data.user.photoData,pixel);assert.equal(publicProfile.data.user.city,'Анапа');assert.equal(publicProfile.data.user.telegramContact,'roman_tennis');assert.equal(publicProfile.data.user.username,undefined);
 assert.equal((await request('/users/demo-unknown-0001','demo-player-0002')).status,404);
 const previousTraining=(await request('/trainings','demo-player-0001')).data.trainings.find(t=>t.id==='11111111-1111-4111-8111-111111111111');
 assert.equal(previousTraining.ntrpMin,3.5);assert.equal(previousTraining.ntrpMax,3.5);
 const start=new Date(Date.now()+4*3600000).toISOString();
 const create=await request('/games','demo-player-0001','POST',{sport:'tennis',kind:'rating',seats:2,city:'Краснодар',courtId:'dinamo',startsAt:start,duration:60,levelMin:2.5,levelMax:3.5,price:1200,note:'Тест',opponentGender:'female'});
 assert.equal(create.status,201);assert.equal(create.data.game.courtAddress,'ул. Красная, 190');assert.equal(create.data.game.opponentGender,'female');assert.equal(create.data.game.creatorGender,'female');assert.equal(create.data.game.creatorNtrp,3.5);assert.equal(create.data.game.creatorRole,'player');const id=create.data.game.id;
 assert.equal((await request(`/games/${id}/join`,'demo-player-0003','POST')).status,403);
 const invalid=await request('/games','demo-player-0001','POST',{sport:'padel',kind:'friendly',seats:4,courtId:'dinamo',startsAt:start,duration:60,levelMin:2.5,levelMax:3.5,price:800});assert.equal(invalid.status,400);
 const join=await request(`/games/${id}/join`,'demo-player-0002','POST');assert.equal(join.status,200);assert.equal(join.data.game.members.length,2);
 assert.equal(join.data.game.members.find(m=>m.id==='demo-player-0001').photoData,pixel);
 assert.equal(join.data.game.members.find(m=>m.id==='demo-player-0002').avatarId,'female-serve');
 assert.equal((await request(`/games/${id}/join`,'demo-player-0002','POST')).status,409);
 assert.equal((await request(`/games/${id}/result`,'demo-player-0001','POST',{score:'6:4, 6:3'})).status,409);
 db.prepare('UPDATE games SET starts_at=? WHERE id=?').run(new Date(Date.now()-3*3600000).toISOString(),id);
 const reported=await request(`/games/${id}/result`,'demo-player-0001','POST',{score:'6:4, 6:3'});assert.equal(reported.status,200);assert.equal(reported.data.game.resultConfirmed,false);
 assert.equal((await request(`/games/${id}/confirm`,'demo-player-0001','POST')).status,409);
 const confirmed=await request(`/games/${id}/confirm`,'demo-player-0002','POST');assert.equal(confirmed.status,200);assert.equal(confirmed.data.game.resultConfirmed,true);
 const winner=(await request('/me','demo-player-0001')).data.user;const loser=(await request('/me','demo-player-0002')).data.user;assert.equal(winner.ntrpLevel,3.5);assert.equal(loser.ntrpLevel,3.5);assert.equal(winner.photoData,pixel);assert.equal(winner.tennis_rating,undefined);
 assert.equal((await request(`/games/${id}/confirm`,'demo-player-0002','POST')).status,409);
});
test('coach registration and avatar persist',async()=>{
 const coach=await request('/profile','demo-coach-0004','POST',{...registration('Мария','female','coach'),coachYears:6,coachSports:['tennis','padel'],photoData:coachPhoto});
 assert.equal(coach.status,200);assert.equal(coach.data.user.role,'coach');assert.equal(coach.data.user.coachYears,6);assert.equal(coach.data.user.avatarId,'female-serve');assert.equal(coach.data.user.ntrpLevel,null);assert.deepEqual(coach.data.user.coachSports,['tennis','padel']);
 assert.equal((await request('/profile','demo-coach-0005','POST',{...registration('Иван','male','coach'),coachSports:[]})).status,400);
 assert.equal((await request('/profile','demo-coach-0005','POST',{...registration('Иван','male','coach'),coachYears:-1})).status,400);
});
test('coach publishes training and players reserve available places',async()=>{
 const start=new Date(Date.now()+48*3600000).toISOString();
 const payload={sport:'tennis',format:'split',seats:2,courtId:'dinamo',startsAt:start,duration:90,ntrpMin:2.5,ntrpMax:4,price:1500,note:'Подача и игра у сетки'};
 assert.equal((await request('/trainings','demo-player-0001','POST',payload)).status,403);
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,courtId:'padel360'})).status,400);
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,sport:'padel',courtId:'dinamo'})).status,400);
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,sport:'badminton'})).status,400);
 const padelTraining=await request('/trainings','demo-coach-0004','POST',{...payload,sport:'padel',courtId:'padel360'});assert.equal(padelTraining.status,201);assert.equal(padelTraining.data.training.sport,'padel');assert.equal(padelTraining.data.training.courtId,'padel360');
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,ntrpMin:4,ntrpMax:2.5})).status,400);
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,ntrpMin:null})).status,400);
 const created=await request('/trainings','demo-coach-0004','POST',payload);assert.equal(created.status,201);assert.equal(created.data.training.sport,'tennis');assert.equal(created.data.training.coachGender,'female');assert.equal(created.data.training.ntrpMin,2.5);assert.equal(created.data.training.ntrpMax,4);assert.equal(created.data.training.format,'split');assert.equal(created.data.training.coachName,'Мария');assert.equal(created.data.training.coachYears,6);assert.equal(created.data.training.coachAvatarId,'female-serve');assert.equal(created.data.training.coachPhotoData,coachPhoto);const id=created.data.training.id;
 const unrestricted=await request('/trainings','demo-coach-0004','POST',{...payload,ntrpMin:null,ntrpMax:null});assert.equal(unrestricted.status,201);assert.equal(unrestricted.data.training.ntrpMin,null);
 assert.equal((await request(`/trainings/${id}/join`,'demo-coach-0004','POST')).status,409);
 assert.equal((await request(`/trainings/${id}/join`,'demo-player-0001','POST')).status,200);
 assert.equal((await request(`/trainings/${id}/join`,'demo-player-0002','POST')).status,200);
 const members=(await request('/trainings','demo-player-0002')).data.trainings.find(t=>t.id===id).members;assert.equal(members.find(m=>m.id==='demo-player-0001').photoData,coachPhoto);assert.equal(members.find(m=>m.id==='demo-player-0002').avatarId,'female-serve');
 assert.equal((await request(`/trainings/${id}/join`,'demo-player-0003','POST')).status,409);
 const listing=await request('/trainings','demo-coach-0004');assert.equal(listing.data.trainings.find(t=>t.id===id).members.length,2);
 const updated=await request('/profile','demo-coach-0004','POST',{...registration('Мария','female','coach'),coachYears:6,coachSports:['tennis'],photoData:coachPhoto});assert.equal(updated.status,200);
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,sport:'padel',courtId:'padel360'})).status,403);
 assert.equal((await request(`/trainings/${id}/leave`,'demo-player-0002','POST')).status,200);
 assert.equal((await request(`/trainings/${id}/join`,'demo-player-0003','POST')).status,200);
});
test('Telegram initData signature and expiry',()=>{
 process.env.BOT_TOKEN='test-secret';const auth_date=String(Math.floor(Date.now()/1000));const user=JSON.stringify({id:123,first_name:'Test'});
 const check=`auth_date=${auth_date}\nuser=${user}`;const secret=crypto.createHmac('sha256','WebAppData').update(process.env.BOT_TOKEN).digest();const hash=crypto.createHmac('sha256',secret).update(check).digest('hex');const raw=new URLSearchParams({user,auth_date,hash}).toString();
 assert.equal(verifyInitData(raw).id,'123');assert.throws(()=>verifyInitData(raw.replace('Test','Evil')),/подпись/);
 const signature='third-party-signature';const signedCheck=`auth_date=${auth_date}\nsignature=${signature}\nuser=${user}`;
 const signedHash=crypto.createHmac('sha256',secret).update(signedCheck).digest('hex');
 const withSignature=new URLSearchParams({user,auth_date,signature,hash:signedHash}).toString();
 assert.equal(verifyInitData(withSignature).id,'123');
 assert.throws(()=>verifyInitData(withSignature.replace(signature,'tampered-signature')),/подпись/);
 delete process.env.BOT_TOKEN;
});
test('only the booking owner can cancel a training request',async()=>{
 const startsAt=new Date(Date.now()+2*86400000).toISOString();
 const created=await request('/bookings','demo-player-0001','POST',{coachId:'anastasia',courtId:'dinamo',startsAt});
 assert.equal(created.status,201);const id=created.data.bookingId;
 assert.equal((await request(`/bookings/${id}`,'demo-player-0002','DELETE')).status,404);
 assert.equal((await request('/bookings','demo-player-0001')).data.bookings.some(b=>b.id===id),true);
 assert.equal((await request(`/bookings/${id}`,'demo-player-0001','DELETE')).status,200);
 assert.equal((await request('/bookings','demo-player-0001')).data.bookings.some(b=>b.id===id),false);
});
test.after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();fs.rmSync(dir,{recursive:true,force:true});});
