import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tennis-go-'));
process.env.DB_PATH=path.join(dir,'test.sqlite');
process.env.ADMIN_DEMO_USER_ID='demo-admin-0009';
const oldDb=new DatabaseSync(process.env.DB_PATH);
oldDb.exec('CREATE TABLE users(id TEXT PRIMARY KEY, name TEXT NOT NULL, username TEXT, tennis_rating INTEGER NOT NULL DEFAULT 1200, padel_rating INTEGER NOT NULL DEFAULT 1200, created_at TEXT NOT NULL)');
oldDb.prepare('INSERT INTO users(id,name,username,created_at) VALUES(?,?,?,?)').run('demo-legacy-0001','Старый игрок','','2026-09-01T00:00:00.000Z');
oldDb.exec('CREATE TABLE trainings(id TEXT PRIMARY KEY, coach_id TEXT NOT NULL REFERENCES users(id), format TEXT NOT NULL, seats INTEGER NOT NULL, court_id TEXT NOT NULL, starts_at TEXT NOT NULL, duration INTEGER NOT NULL, avg_ntrp REAL, price INTEGER NOT NULL, note TEXT NOT NULL, created_at TEXT NOT NULL)');
oldDb.prepare('INSERT INTO trainings VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('11111111-1111-4111-8111-111111111111','demo-legacy-0001','individual',1,'dinamo',new Date(Date.now()+86400000).toISOString(),60,3.5,1000,'Старая тренировка','2026-09-01T00:00:00.000Z');
oldDb.close();
const {server,db,verifyInitData,sendNextBotMessage,processEventReminders,processTrainingAds,processMatchPrompts,handleBotUpdate,notificationButton,earliestStart}=await import('../server.mjs');
assert.equal(db.prepare('PRAGMA table_info(users)').all().some(column=>column.name==='ntrp_level'),true);
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
async function request(route,user,method='GET',body){const res=await fetch(base+'/api'+route,{method,headers:{'x-demo-user':user,'x-demo-name':encodeURIComponent(user==='demo-player-0001'?'Роман':'Вика'),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json()};}
const registration=(name,gender,role='player')=>({name:name.includes(' ')?name:name+' Тестов',gender,role,phone:'+7 999 123-45-67',telegramContact:role==='coach'?'coach_test':null,playingYears:2,ntrpLevel:role==='coach'?null:3.5,about:role==='coach'?'Веду занятия по теннису':'Играю по выходным',coachYears:role==='coach'?1:null,avatarId:gender==='female'?'female-serve':'male-cap',photoData:null});
const coachPhoto='data:image/jpeg;base64,'+Buffer.from([0xff,0xd8,0xff,0xd9]).toString('base64');
test('game lifecycle and mutual confirmation preserve self selected NTRP',async()=>{
 assert.equal((await request('/me','demo-legacy-0001')).data.user.registered,0);
 assert.equal((await request('/me','demo-player-0001')).data.user.registered,0);
 assert.equal((await request('/games','demo-player-0001')).status,403);
 const pixel='data:image/jpeg;base64,'+Buffer.from([0xff,0xd8,0xff,0xd9]).toString('base64');
 const profile=await request('/profile','demo-player-0001','POST',{...registration('Роман Игрок','female'),city:'Анапа',phone:'+7 (999) 123-45-67',telegramContact:'@roman_tennis',photoData:pixel});
 assert.equal((await request('/profile','demo-player-0001','POST',{...registration('Роман Игрок','female'),firstName:'Роман',lastName:''})).status,400);
 const separate=await request('/profile','demo-player-0001','POST',{...registration('Роман Игрок','female'),firstName:'Роман',lastName:'Игрок',city:'Анапа',photoData:pixel});assert.equal(separate.status,200);assert.equal(separate.data.user.name,'Роман Игрок');
 assert.equal(profile.status,200);assert.equal(profile.data.user.name,'Роман Игрок');assert.equal(profile.data.user.ntrpLevel,3.5);assert.equal(profile.data.user.photoData,pixel);assert.equal(profile.data.user.registered,1);assert.equal(profile.data.user.city,'Анапа');assert.equal(profile.data.user.phone,'+7 (999) 123-45-67');assert.equal(profile.data.user.telegramContact,'roman_tennis');
 const emptyProgress=await request('/progress','demo-player-0001');assert.equal(emptyProgress.status,200);assert.equal(emptyProgress.data.totalGames,0);assert.equal(emptyProgress.data.totalTrainings,0);assert.equal(emptyProgress.data.months.length,5);
 assert.equal((await request('/profile','demo-player-0001','POST',{...registration('Роман','female'),city:'Неизвестный город'})).status,400);
 assert.equal((await request('/profile','demo-player-0001','POST',{...registration('Роман','female'),phone:'123'})).status,400);
 assert.equal((await request('/profile','demo-player-0001','POST',{...registration('Роман','female'),telegramContact:'https://t.me/example'})).status,400);
 assert.equal((await request('/profile','demo-player-0001','POST',{...registration('','female'),ntrpLevel:8})).status,400);
 assert.equal((await request('/profile','demo-player-0002','POST',registration('Вика','female'))).status,200);
 assert.equal((await request('/profile','demo-player-0003','POST',registration('Игорь','male'))).status,200);
 const publicProfile=await request('/users/demo-player-0001','demo-player-0002');assert.equal(publicProfile.status,200);assert.equal(publicProfile.data.user.name,'Роман И.');assert.equal(publicProfile.data.user.ntrpLevel,3.5);assert.equal(publicProfile.data.user.photoData,pixel);assert.equal(publicProfile.data.user.city,'Анапа');assert.equal(publicProfile.data.user.telegramContact,null);assert.equal(publicProfile.data.user.username,undefined);
 assert.equal((await request('/users/demo-unknown-0001','demo-player-0002')).status,404);
 const previousTraining=(await request('/trainings','demo-player-0001')).data.trainings.find(t=>t.id==='11111111-1111-4111-8111-111111111111');
 assert.equal(previousTraining.ntrpMin,3.5);assert.equal(previousTraining.ntrpMax,3.5);
 const start=new Date(Date.now()+4*3600000).toISOString();
 const create=await request('/games','demo-player-0001','POST',{sport:'tennis',kind:'rating',seats:2,city:'Краснодар',courtId:'dinamo',startsAt:start,duration:60,levelMin:2.5,levelMax:3.5,price:1200,note:'Тест',opponentGender:'female'});
 assert.equal(create.status,201);assert.equal(create.data.game.courtAddress,'ул. Красная, 190');assert.equal(create.data.game.creatorName,'Роман И.');assert.equal(create.data.game.creatorPhotoData,pixel);assert.equal(create.data.game.opponentGender,'female');assert.equal(create.data.game.creatorGender,'female');assert.equal(create.data.game.creatorNtrp,3.5);assert.equal(create.data.game.creatorRole,'player');const id=create.data.game.id;
 assert.ok((await request('/notifications','demo-player-0002')).data.items.some(n=>n.body.startsWith('Новая игра:')));
 assert.equal((await request(`/games/${id}/join`,'demo-player-0003','POST')).status,403);
 const invalid=await request('/games','demo-player-0001','POST',{sport:'padel',kind:'friendly',seats:4,courtId:'dinamo',startsAt:start,duration:60,levelMin:2.5,levelMax:3.5,price:800});assert.equal(invalid.status,400);
 const join=await request(`/games/${id}/join`,'demo-player-0002','POST');assert.equal(join.status,200);assert.equal(join.data.game.members.length,2);
 assert.equal(join.data.game.members.find(m=>m.id==='demo-player-0001').photoData,pixel);
 assert.equal(join.data.game.members.find(m=>m.id==='demo-player-0002').avatarId,'female-serve');
 assert.equal((await request(`/games/${id}/join`,'demo-player-0002','POST')).status,409);
 assert.equal((await request(`/games/${id}/result`,'demo-player-0001','POST',{score:'6:4, 6:3'})).status,409);
 db.prepare('UPDATE games SET starts_at=? WHERE id=?').run(new Date(Date.now()-3*3600000).toISOString(),id);
 assert.equal((await request(`/games/${id}/result`,'demo-player-0001','POST',{score:'6:4, 6:3'})).status,409);
 assert.equal((await request(`/games/${id}/attend`,'demo-player-0001','POST')).status,200);
 assert.equal((await request(`/games/${id}/confirm-attendance`,'demo-player-0002','POST')).status,200);
 assert.equal((await request(`/games/${id}/result`,'demo-player-0001','POST',{score:'9:2, 6:3'})).status,400);
 const reported=await request(`/games/${id}/result`,'demo-player-0001','POST',{score:'6:4, 6:3'});assert.equal(reported.status,200);assert.equal(reported.data.game.resultConfirmed,false);
 assert.equal((await request(`/games/${id}/dispute`,'demo-player-0002','POST',{reason:'Неверный второй сет'})).status,200);
 assert.equal((await request(`/games/${id}/confirm`,'demo-player-0002','POST')).status,409);
 assert.equal((await request(`/games/${id}/result`,'demo-player-0002','POST',{score:'6:4, 6:3'})).status,403);
 assert.equal((await request(`/games/${id}/result`,'demo-player-0001','POST',{score:'6:4, 6:3'})).status,200);
 assert.equal((await request(`/games/${id}/confirm`,'demo-player-0001','POST')).status,409);
 const confirmed=await request(`/games/${id}/confirm`,'demo-player-0002','POST');assert.equal(confirmed.status,200);assert.equal(confirmed.data.game.resultConfirmed,true);
 const winner=(await request('/me','demo-player-0001')).data.user;const loser=(await request('/me','demo-player-0002')).data.user;assert.equal(winner.ntrpLevel,3.5);assert.equal(loser.ntrpLevel,3.5);assert.equal(winner.photoData,pixel);assert.equal(winner.tennis_rating,undefined);
 assert.ok(winner.ratings.tennis.rating>1500&&loser.ratings.tennis.rating<1500);
 assert.equal(winner.ratings.tennis.matches,1);assert.equal(winner.ratings.padel.matches,0);
 assert.equal((await request('/ratings/history','demo-player-0001')).data.events.length,1);
 const progress=await request('/progress','demo-player-0001');assert.equal(progress.status,200);assert.equal(progress.data.totalGames,1);assert.equal(progress.data.months.at(-1).games,1);assert.equal(progress.data.totalTrainings,0);assert.equal(progress.data.months.at(-1).rating,Math.round(winner.ratings.tennis.rating));assert.ok(progress.data.ratingDelta>0);
 const notifications=await request('/notifications','demo-player-0002');assert.ok(notifications.data.unread>0);
 assert.equal((await request('/notifications/read','demo-player-0002','POST')).status,200);
 assert.equal((await request('/notifications','demo-player-0002')).data.unread,0);
 assert.equal((await request(`/games/${id}/confirm`,'demo-player-0002','POST')).status,409);
});
test('coach registration and avatar persist',async()=>{
 const coach=await request('/profile','demo-coach-0004','POST',{...registration('Мария','female','coach'),coachYears:6,coachSports:['tennis','padel'],coachCourts:['alfa-tennis','dinamo'],coachAchievements:'Призёр региональных турниров',photoData:coachPhoto});
 assert.equal(coach.status,200);assert.equal(coach.data.user.role,'coach');assert.equal(coach.data.user.coachYears,6);assert.equal(coach.data.user.avatarId,'female-serve');assert.equal(coach.data.user.ntrpLevel,null);assert.deepEqual(coach.data.user.coachSports,['tennis','padel']);
 assert.deepEqual(coach.data.user.coachCourts,['alfa-tennis','dinamo']);assert.equal(coach.data.user.coachAchievements,'Призёр региональных турниров');
 const publicCoach=await request('/users/demo-coach-0004','demo-player-0002');assert.deepEqual(publicCoach.data.user.coachCourts,['alfa-tennis','dinamo']);assert.equal(publicCoach.data.user.coachAchievements,'Призёр региональных турниров');
 const listed=(await request('/users?role=coach','demo-player-0002')).data.users.find(u=>u.id==='demo-coach-0004');assert.equal(listed.coachYears,6);assert.deepEqual(listed.coachCourts,['alfa-tennis','dinamo']);
 assert.equal((await request('/profile','demo-coach-0004','POST',{...registration('Мария','female','coach'),coachSports:['padel'],coachCourts:['dinamo']})).status,400);
 assert.equal((await request('/registration-courts','demo-new-coach-0001')).status,200);
 assert.equal((await request('/profile/city','demo-coach-0004','PATCH',{city:'Выдуманный город'})).status,400);
 const moved=await request('/profile/city','demo-coach-0004','PATCH',{city:'Анапа'});assert.equal(moved.status,200);assert.equal(moved.data.user.city,'Анапа');assert.deepEqual(moved.data.user.coachCourts,[]);assert.equal(moved.data.user.coachAchievements,'Призёр региональных турниров');
 assert.equal((await request('/profile/city','demo-coach-0004','PATCH',{city:'Краснодар'})).status,200);
 assert.equal((await request('/profile','demo-coach-0005','POST',{...registration('Иван','male','coach'),coachSports:[]})).status,400);
 assert.equal((await request('/profile','demo-coach-0005','POST',{...registration('Иван','male','coach'),coachYears:-1})).status,400);
});
test('sport preference persists and tournament poster is published once',async()=>{
 const tournament=(await request('/news','demo-player-0002')).data.items.find(item=>item.id==='tennis-go-tournament-2026-10-04');
 assert.equal(tournament.sport,'tennis');assert.equal(tournament.imagePath,'/assets/tennis-tournament-2026-10-04.jpg');
 assert.ok(tournament.body.includes('@aiidamar'));
 assert.equal((await request('/preferences/sports','demo-player-0002','PATCH',{sports:['padel']})).status,200);
 assert.deepEqual((await request('/me','demo-player-0002')).data.user.preferredSports,['padel']);
 assert.equal((await request('/preferences/sports','demo-player-0002','PATCH',{sports:['padel','padel']})).status,400);
 assert.equal((await request('/preferences/sports','demo-player-0002','PATCH',{sports:[]})).status,200);
 assert.deepEqual((await request('/me','demo-player-0002')).data.user.preferredSports,[]);
});
test('only administrator publishes news and all registered participants get one notification',async()=>{
 assert.equal((await request('/news','demo-player-0001','POST',{title:'Новости кортов',body:'Открыта регистрация на новый турнир'})).status,403);
 assert.equal((await request('/profile','demo-admin-0009','POST',registration('Администратор','male'))).status,200);
 assert.equal((await request('/news','demo-admin-0009','POST',{title:'Коротко',body:'Мало'})).status,400);
 const before=db.prepare("SELECT COUNT(*) AS n FROM notifications WHERE user_id=? AND body LIKE 'Новость:%'").get('demo-player-0002').n;
 const created=await request('/news','demo-admin-0009','POST',{title:'Новый турнир Tennis GO',body:'Открыта регистрация на новый турнир для всех участников.'});
 assert.equal(created.status,201);
 assert.equal((await request('/news','demo-player-0002')).data.items[0].title,'Новый турнир Tennis GO');
 assert.equal(db.prepare("SELECT COUNT(*) AS n FROM notifications WHERE user_id=? AND body LIKE 'Новость:%'").get('demo-player-0002').n,before+1);
 assert.equal(db.prepare("SELECT COUNT(*) AS n FROM notifications WHERE user_id=? AND body LIKE 'Новость:%'").get('demo-admin-0009').n,1);
 assert.equal(db.prepare('SELECT COUNT(*) AS n FROM bot_outbox').get().n,0);
});
test('coach publishes training and players reserve available places',async()=>{
 const start=new Date(Date.now()+48*3600000).toISOString();
 const payload={sport:'tennis',format:'split',seats:2,courtId:'dinamo',startsAt:start,duration:90,ntrpMin:2.5,ntrpMax:4,price:1500,note:'Подача и игра у сетки'};
 assert.equal((await request('/trainings','demo-player-0001','POST',payload)).status,403);
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,courtId:'padel360'})).status,400);
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,sport:'padel',courtId:'dinamo'})).status,400);
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,sport:'badminton'})).status,400);
 const padelTraining=await request('/trainings','demo-coach-0004','POST',{...payload,sport:'padel',courtId:'padel360'});assert.equal(padelTraining.status,201);assert.equal(padelTraining.data.training.sport,'padel');assert.equal(padelTraining.data.training.courtId,'padel360');
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,ntrpMin:4,ntrpMax:2.5})).status,400);
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,ntrpMin:null})).status,400);
 const created=await request('/trainings','demo-coach-0004','POST',payload);assert.equal(created.status,201);assert.equal(created.data.training.sport,'tennis');assert.equal(created.data.training.coachGender,'female');assert.equal(created.data.training.ntrpMin,2.5);assert.equal(created.data.training.ntrpMax,4);assert.equal(created.data.training.format,'split');assert.equal(created.data.training.coachName,'Мария Тестов');assert.equal(created.data.training.coachYears,6);assert.equal(created.data.training.coachAvatarId,'female-serve');assert.equal(created.data.training.coachPhotoData,coachPhoto);const id=created.data.training.id;
 assert.ok((await request('/notifications','demo-player-0002')).data.items.some(n=>n.body.includes('Есть места на тренировку:')&&n.body.includes('1500 ₽/чел.')));
 const unrestricted=await request('/trainings','demo-coach-0004','POST',{...payload,ntrpMin:null,ntrpMax:null});assert.equal(unrestricted.status,201);assert.equal(unrestricted.data.training.ntrpMin,null);
 assert.equal((await request(`/trainings/${id}/join`,'demo-coach-0004','POST')).status,409);
 assert.equal((await request(`/trainings/${id}/join`,'demo-player-0001','POST')).status,200);
 assert.equal((await request(`/trainings/${id}/join`,'demo-player-0002','POST')).status,200);
 const members=(await request('/trainings','demo-player-0002')).data.trainings.find(t=>t.id===id).members;assert.equal(members.find(m=>m.id==='demo-player-0001').photoData,coachPhoto);assert.equal(members.find(m=>m.id==='demo-player-0002').avatarId,'female-serve');
 assert.equal((await request(`/trainings/${id}/join`,'demo-player-0003','POST')).status,409);
 const listing=await request('/trainings','demo-coach-0004');assert.equal(listing.data.trainings.find(t=>t.id===id).members.length,2);
 const updated=await request('/profile','demo-coach-0004','POST',{...registration('Мария','female','coach'),coachYears:6,coachSports:['tennis'],photoData:coachPhoto});assert.equal(updated.status,200);
 assert.equal((await request('/trainings','demo-coach-0004','POST',{...payload,sport:'padel',courtId:'padel360'})).status,403);
 assert.equal((await request(`/trainings/${id}/leave`,'demo-player-0002','POST')).status,200);
 assert.equal((await request(`/trainings/${id}/join`,'demo-player-0003','POST')).status,200);
 assert.equal((await request(`/trainings/${id}/review`,'demo-player-0001','POST',{score:5,comment:'Отличная тренировка'})).status,403);
 db.prepare('UPDATE trainings SET starts_at=? WHERE id=?').run(new Date(Date.now()-3*3600000).toISOString(),id);
 assert.equal((await request(`/trainings/${id}/review`,'demo-player-0001','POST',{score:5,comment:'Отличная тренировка'})).status,403);
 assert.equal((await request(`/trainings/${id}/complete`,'demo-player-0001','POST')).status,403);
 assert.equal((await request(`/trainings/${id}/complete`,'demo-coach-0004','POST')).status,200);
 assert.equal((await request(`/trainings/${id}/review`,'demo-coach-0004','POST',{score:5,comment:'Отличная тренировка'})).status,403);
 assert.equal((await request(`/trainings/${id}/review`,'demo-player-0001','POST',{score:5,comment:'Отличная тренировка'})).status,200);
 assert.equal((await request(`/trainings/${id}/review`,'demo-player-0001','POST',{score:1,comment:'Повторный отзыв'})).status,409);
 assert.equal((await request('/users/demo-coach-0004','demo-player-0001')).data.user.reviews[0].score,5);
});
test('absence report stays unrated and can be contested',async()=>{
 const startsAt=new Date(Date.now()+4*3600000).toISOString(),payload={sport:'padel',kind:'rating',seats:2,courtId:'padel360',startsAt,duration:60,levelMin:2.5,levelMax:4,price:800,note:'Тест неявки',opponentGender:'any'};
 const g=(await request('/games','demo-player-0001','POST',payload)).data.game;
 assert.equal((await request(`/games/${g.id}/join`,'demo-player-0002','POST')).status,200);
 db.prepare('UPDATE games SET starts_at=? WHERE id=?').run(new Date(Date.now()-3*3600000).toISOString(),g.id);
 assert.equal((await request(`/games/${g.id}/report-absence`,'demo-player-0001','POST',{reason:'Соперник не пришёл'})).status,200);
 assert.equal((await request(`/games/${g.id}/attend`,'demo-player-0002','POST')).status,409);
 assert.equal((await request(`/games/${g.id}/contest-absence`,'demo-player-0002','POST')).status,200);
 assert.equal((await request(`/games/${g.id}/contest-absence`,'demo-player-0002','POST')).status,409);
 assert.equal((await request('/me','demo-player-0001')).data.user.ratings.padel.matches,0);
});
test('authors edit and cancel listings; chats remain tied to their announcement',async()=>{
 const startsAt=new Date(Date.now()+5*86400000).toISOString();
 const gamePayload={sport:'tennis',kind:'friendly',seats:2,courtId:'dinamo',startsAt,duration:90,levelMin:2.5,levelMax:3.5,price:900,note:'Ищу партнёра',opponentGender:'any'};
 const game=(await request('/games','demo-player-0001','POST',gamePayload)).data.game;
 assert.equal((await request(`/games/${game.id}`,'demo-player-0002','PATCH',{...gamePayload,price:800})).status,403);
 assert.equal((await request(`/games/${game.id}`,'demo-player-0002','DELETE')).status,403);
 const edited=await request(`/games/${game.id}`,'demo-player-0001','PATCH',{...gamePayload,price:800,courtId:'vopreki-tennis'});
 assert.equal(edited.status,200);assert.equal(edited.data.game.price,800);assert.equal(edited.data.game.venue,'Спортивная академия «Вопреки»');
 const sent=await request(`/chats/game/${game.id}/demo-player-0001`,'demo-player-0002','POST',{message:'Добрый день, игра состоится?'});
 assert.equal(sent.status,200);assert.equal(sent.data.messages[0].body,'Добрый день, игра состоится?');
 assert.equal((await request(`/chats/game/${game.id}`,'demo-player-0001')).data.threads[0].id,'demo-player-0002');
 const replied=await request(`/chats/game/${game.id}/demo-player-0002`,'demo-player-0001','POST',{message:'Да, жду вас!'});
 assert.equal(replied.data.messages.length,2);
 assert.equal((await request(`/chats/game/${game.id}/demo-player-0003`,'demo-player-0002','GET')).status,403);
 assert.equal((await request(`/games/${game.id}`,'demo-player-0001','DELETE')).data.game.cancelled,true);
 assert.equal((await request(`/games/${game.id}/join`,'demo-player-0002','POST')).status,409);
 assert.equal((await request(`/games/${game.id}`,'demo-player-0001','PATCH',gamePayload)).status,409);
 const trainingPayload={sport:'tennis',format:'split',seats:2,courtId:'dinamo',startsAt,duration:90,ntrpMin:null,ntrpMax:null,price:1500,note:'У сетки'};
 const training=(await request('/trainings','demo-coach-0004','POST',trainingPayload)).data.training;
 assert.equal((await request(`/trainings/${training.id}/join`,'demo-player-0002','POST')).status,200);
 assert.equal((await request(`/trainings/${training.id}/join`,'demo-player-0003','POST')).status,200);
 assert.equal((await request(`/trainings/${training.id}`,'demo-player-0002','PATCH',{...trainingPayload,price:1800})).status,403);
 assert.equal((await request(`/trainings/${training.id}`,'demo-coach-0004','PATCH',{...trainingPayload,format:'individual',seats:1})).status,409);
 assert.equal((await request(`/trainings/${training.id}`,'demo-coach-0004','PATCH',{...trainingPayload,format:'individual',seats:0})).status,400);
 const updated=await request(`/trainings/${training.id}`,'demo-coach-0004','PATCH',{...trainingPayload,price:1800});
 assert.equal(updated.status,200);assert.equal(updated.data.training.price,1800);
 assert.equal((await request(`/chats/training/${training.id}/demo-coach-0004`,'demo-player-0002','POST',{message:'Можно прийти чуть раньше?'})).status,200);
 assert.equal((await request(`/trainings/${training.id}`,'demo-coach-0004','DELETE')).data.training.cancelled,true);
 assert.equal((await request(`/trainings/${training.id}/join`,'demo-player-0003','POST')).status,409);
});
test('weather endpoint caches hourly temperature and condition codes',async()=>{
 const original=globalThis.fetch;let upstreamCalls=0;
 globalThis.fetch=(url,options)=>{
   if(url instanceof URL&&url.hostname.endsWith('open-meteo.com')){upstreamCalls++;return Promise.resolve({ok:true,json:async()=>({hourly:{time:['2026-09-26T12:00'],temperature_2m:[22.6],weather_code:[3]}})});}
   return original(url,options);
 };
 try{
   const first=await request('/weather','demo-player-0001');const second=await request('/weather','demo-player-0001');
   assert.equal(first.status,200);assert.deepEqual(first.data.hours,[{time:'2026-09-26T12:00Z',temperature:22.6,code:3}]);
   assert.deepEqual(second.data.hours,first.data.hours);assert.equal(upstreamCalls,1);
 }finally{globalThis.fetch=original;}
});
test('registered user directory and unread direct and listing conversations',async()=>{
 const users=await request('/users?q=Мария','demo-player-0001');
 assert.equal(users.status,200);assert.equal(users.data.users.length,1);assert.equal(users.data.users[0].role,'coach');
 const coaches=await request('/users?role=coach','demo-player-0001');assert.equal(coaches.status,200);assert.ok(coaches.data.users.length>0&&coaches.data.users.every(u=>u.role==='coach'));
 assert.equal((await request('/users?role=club','demo-player-0001')).status,400);
 assert.equal(users.data.users[0].phone,undefined);
 assert.equal((await request('/users?q=Роман','demo-player-0001')).data.users.some(u=>u.id==='demo-player-0001'),false);
 assert.equal((await request('/direct/demo-unknown-0001','demo-player-0001','POST',{message:'Привет'})).status,404);
 const sent=await request('/direct/demo-player-0001','demo-player-0002','POST',{message:'Привет, сыграем?'});
 assert.equal(sent.status,200);assert.equal(sent.data.messages.at(-1).body,'Привет, сыграем?');
 const inbox=await request('/inbox','demo-player-0001');
 assert.ok(inbox.data.threads.some(t=>t.key==='direct:demo-player-0002'&&t.unread===1));
 assert.ok(inbox.data.unread>=1);
 assert.equal((await request('/direct/demo-player-0002','demo-player-0001')).data.messages.at(-1).body,'Привет, сыграем?');
 assert.equal((await request('/inbox','demo-player-0001')).data.threads.find(t=>t.key==='direct:demo-player-0002').unread,0);
 const start=new Date(Date.now()+4*86400000).toISOString();
 const game=(await request('/games','demo-player-0001','POST',{sport:'tennis',kind:'friendly',seats:2,courtId:'dinamo',startsAt:start,duration:60,levelMin:2.5,levelMax:3.5,price:1000,note:'',opponentGender:'any'})).data.game;
 assert.equal((await request(`/chats/game/${game.id}/demo-player-0001`,'demo-player-0003','POST',{message:'Есть свободное место?'})).status,200);
 assert.equal((await request('/inbox','demo-player-0001')).data.threads.find(t=>t.key===`game:${game.id}:demo-player-0003`).unread,1);
 assert.equal((await request(`/chats/game/${game.id}/demo-player-0003`,'demo-player-0001')).status,200);
 assert.equal((await request('/inbox','demo-player-0001')).data.threads.find(t=>t.key===`game:${game.id}:demo-player-0003`).unread,0);
});
test('Telegram initData signature and expiry',()=>{
 process.env.BOT_TOKEN='test-secret';const auth_date=String(Math.floor(Date.now()/1000));const user=JSON.stringify({id:123,first_name:'Test'});
 const check=`auth_date=${auth_date}\nuser=${user}`;const secret=crypto.createHmac('sha256','WebAppData').update(process.env.BOT_TOKEN).digest();const hash=crypto.createHmac('sha256',secret).update(check).digest('hex');const raw=new URLSearchParams({user,auth_date,hash}).toString();
 assert.equal(verifyInitData(raw).id,'123');assert.throws(()=>verifyInitData(raw.replace('Test','Evil')),/подпись/);
 const signature='third-party-signature';const signedCheck=`auth_date=${auth_date}\nsignature=${signature}\nuser=${user}`;
 const signedHash=crypto.createHmac('sha256',secret).update(signedCheck).digest('hex');
 const withSignature=new URLSearchParams({user,auth_date,signature,hash:signedHash}).toString();
 assert.equal(verifyInitData(withSignature).id,'123');
 assert.throws(()=>verifyInitData(withSignature.replace(signature,'tampered-signature')),/подпись/);
 delete process.env.BOT_TOKEN;
});
test('only the booking owner can cancel a training request',async()=>{
 const startsAt=new Date(Date.now()+2*86400000).toISOString();
 const created=await request('/bookings','demo-player-0001','POST',{coachId:'anastasia',courtId:'dinamo',startsAt});
 assert.equal(created.status,201);const id=created.data.bookingId;
 assert.equal((await request(`/bookings/${id}`,'demo-player-0002','DELETE')).status,404);
 assert.equal((await request('/bookings','demo-player-0001')).data.bookings.some(b=>b.id===id),true);
 assert.equal((await request(`/bookings/${id}`,'demo-player-0001','DELETE')).status,200);
 assert.equal((await request('/bookings','demo-player-0001')).data.bookings.some(b=>b.id===id),false);
});
test('approval requests hold places only after organizer accepts, with rejection and trainer flow',async()=>{
 const start=new Date(Date.now()+5*86400000).toISOString();
 assert.equal((await request('/profile','demo-player-0005','POST',{...registration('Лена','female'),ntrpLevel:1,city:'Волгоград'})).status,200);
 const gamePayload={sport:'tennis',kind:'rating',seats:2,courtId:'dinamo',startsAt:start,duration:60,levelMin:1,levelMax:4,price:1200,note:'',opponentGender:'female',requiresApproval:true};
 const created=await request('/games','demo-player-0001','POST',gamePayload);
 assert.equal(created.status,201);const id=created.data.game.id;
 assert.equal(created.data.game.requiresApproval,true);
 assert.equal((await request(`/games/${id}/join`,'demo-player-0003','POST')).status,403);
 const pending=await request(`/games/${id}/join`,'demo-player-0002','POST');
 assert.equal(pending.status,200);assert.equal(pending.data.game.joined,false);
 assert.equal(pending.data.game.requestStatus,'pending');assert.equal(pending.data.game.members.length,1);
 assert.equal(pending.data.game.requests.length,0);
 assert.equal((await request(`/games/${id}/join`,'demo-player-0002','POST')).status,409);
 assert.equal((await request(`/games/${id}`,'demo-player-0001')).data.game.requests.length,1);
 assert.equal((await request(`/games/${id}/requests/demo-player-0002/approve`,'demo-player-0005','POST')).status,403);
 assert.equal((await request(`/games/${id}/join`,'demo-player-0005','POST')).data.game.requestStatus,'pending');
 const accepted=await request(`/games/${id}/requests/demo-player-0002/approve`,'demo-player-0001','POST');
 assert.equal(accepted.status,200);assert.equal(accepted.data.game.members.length,2);
 assert.equal((await request(`/games/${id}`,'demo-player-0002')).data.game.joined,true);
 assert.equal((await request(`/games/${id}/requests/demo-player-0005/approve`,'demo-player-0001','POST')).status,409);
 assert.equal((await request(`/games/${id}/requests/demo-player-0005/reject`,'demo-player-0001','POST')).status,200);
 assert.equal((await request(`/games/${id}`,'demo-player-0005')).data.game.requestStatus,'rejected');
 assert.equal((await request(`/games/${id}/requests/demo-player-0005/reject`,'demo-player-0001','POST')).status,409);
 const leaderboard=await request('/leaderboard?sport=tennis','demo-player-0001');
 assert.equal(leaderboard.status,200);assert.ok(leaderboard.data.players.every(p=>p.matches>0));
 assert.equal((await request('/leaderboard?sport=bad','demo-player-0001')).status,400);
 const trainingPayload={sport:'tennis',format:'split',seats:2,courtId:'dinamo',startsAt:start,duration:60,ntrpMin:null,ntrpMax:null,price:2500,note:'',requiresApproval:true};
 const training=(await request('/trainings','demo-coach-0004','POST',trainingPayload)).data.training;
 assert.equal((await request(`/trainings/${training.id}/join`,'demo-player-0005','POST')).data.training.requestStatus,'pending');
 assert.equal((await request(`/trainings/${training.id}`,'demo-coach-0004','PATCH',{...trainingPayload,price:2300})).data.training.requests.length,1);
 assert.equal((await request(`/trainings/${training.id}/requests/demo-player-0005/reject`,'demo-coach-0004','POST')).status,200);
 assert.equal((await request('/trainings','demo-player-0005')).data.trainings.find(t=>t.id===training.id).members.length,0);
 assert.equal((await request(`/trainings/${training.id}/join`,'demo-player-0005','POST')).data.training.requestStatus,'pending');
 const approved=await request(`/trainings/${training.id}/requests/demo-player-0005/approve`,'demo-coach-0004','POST');
 assert.equal(approved.status,200);assert.equal(approved.data.training.members.length,1);
 assert.equal((await request('/trainings','demo-player-0005')).data.trainings.find(t=>t.id===training.id).joined,true);
});
test('club registration, administrator approval and private booking calendar',async()=>{
 process.env.ADMIN_DEMO_USER_ID='demo-player-0001';
 const clubId='demo-club-0007',club={role:'club',name:'Наталья',clubName:'Теннис Парк',clubAddress:'ул. Тестовая, 12',city:'Ростов-на-Дону',clubPhone:'+7 900 123-45-67',clubSports:['tennis','padel'],clubPhotoData:coachPhoto,clubSurface:'hard',opensAt:'08:00',closesAt:'22:00',hourlyPrice:1500};
 try{
   assert.equal((await request('/profile',clubId,'POST',{...club,clubPhotoData:null})).status,400);
   const saved=await request('/profile',clubId,'POST',club);assert.equal(saved.status,200);assert.equal(saved.data.user.club.status,'pending');
   assert.equal(saved.data.user.club.photoData,coachPhoto);assert.equal(saved.data.user.club.hourlyPrice,1500);
   assert.equal((await request('/games',clubId)).status,403);
   assert.equal((await request('/catalog','demo-player-0001')).data.courts.some(c=>c.clubId===clubId),false);
   assert.equal((await request('/admin/clubs','demo-player-0002')).status,403);
   const review=(await request('/admin/clubs','demo-player-0001')).data.clubs.find(c=>c.ownerId===clubId);
   assert.equal(review.photoData,coachPhoto);assert.equal(review.surface,'hard');assert.equal(review.hourlyPrice,1500);
   assert.equal((await request(`/admin/clubs/${clubId}/approve`,'demo-player-0001','POST')).status,200);
   assert.equal((await request(`/admin/clubs/${clubId}/approve`,'demo-player-0001','POST')).status,409);
   const courts=(await request('/catalog','demo-player-0001')).data.courts;
   assert.ok(courts.some(c=>c.clubId===clubId&&c.sport==='tennis'&&c.city==='Ростов-на-Дону'&&c.image===coachPhoto&&c.surface==='hard'&&c.opensAt==='08:00'&&c.closesAt==='22:00'&&c.hourlyPrice===1500));
   const startsAt=new Date(Date.now()+7*86400000).toISOString();
   assert.equal((await request('/court-bookings','demo-player-0002','POST',{clubId,sport:'tennis',startsAt,duration:90})).status,409);
   const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(startsAt));
   const calendar=await request('/club/calendar?date='+date,clubId);assert.equal(calendar.status,200);assert.equal(calendar.data.reservations.length,0);
   assert.equal((await request('/club/calendar?date='+date,'demo-player-0001')).status,403);
 }finally{delete process.env.ADMIN_DEMO_USER_ID;}
});
test('doubles rating requires all four to confirm attendance and score',async()=>{
 const fourth='demo-player-0006';assert.equal((await request('/profile',fourth,'POST',registration('Саша','male'))).status,200);
 const startsAt=new Date(Date.now()+4*86400000).toISOString();
 const created=await request('/games','demo-player-0001','POST',{sport:'tennis',kind:'rating',seats:4,courtId:'dinamo',startsAt,duration:60,levelMin:1,levelMax:7,price:800,note:'',opponentGender:'any'});
 assert.equal(created.status,201);const id=created.data.game.id;
 for(const user of ['demo-player-0002','demo-player-0005',fourth])assert.equal((await request(`/games/${id}/join`,user,'POST')).status,200);
 const teams=(await request(`/games/${id}`,'demo-player-0001')).data.game.members;
 assert.deepEqual(teams.map(m=>m.team),['A','B','A','B']);
 db.prepare('UPDATE games SET starts_at=? WHERE id=?').run(new Date(Date.now()-3*3600000).toISOString(),id);
 assert.equal((await request(`/games/${id}/result`,'demo-player-0001','POST',{score:'6:4, 6:3'})).status,409);
 for(const [i,user] of ['demo-player-0001','demo-player-0002','demo-player-0005',fourth].entries()){
   const confirmed=await request(`/games/${id}/attend`,user,'POST');assert.equal(confirmed.status,200);assert.equal(confirmed.data.game.attendanceCount,i+1);
 }
 assert.equal((await request(`/games/${id}/result`,'demo-player-0002','POST',{score:'6:4, 6:3'})).status,403);
 assert.equal((await request(`/games/${id}/result`,'demo-player-0001','POST',{score:'6:4, 6:3'})).status,200);
 for(const [i,user] of ['demo-player-0002','demo-player-0005',fourth].entries()){
   const confirmed=await request(`/games/${id}/confirm`,user,'POST');assert.equal(confirmed.status,200);assert.equal(confirmed.data.game.resultConfirmed,i===2);
 }
 for(const user of ['demo-player-0001','demo-player-0002','demo-player-0005',fourth])assert.ok((await request('/me',user)).data.user.ratings.tennis.matches>=1);
});
test('monthly event counts confirmed rating matches and shows real leaders',async()=>{
 const event=await request('/events/marathon','demo-player-0001');
 assert.equal(event.status,200);assert.equal(event.data.goal,20);assert.match(event.data.month,/^\d{4}-\d{2}$/);
 assert.equal(event.data.earned,event.data.games>=20);
 assert.ok(event.data.games>=0);assert.ok(event.data.leaders.length<=3);
 for(const leader of event.data.leaders)assert.ok(leader.games>0);
 const confirmedThisMonth=db.prepare("SELECT COUNT(*) AS n FROM participants p JOIN games g ON g.id=p.game_id WHERE p.user_id=? AND g.kind='rating' AND g.result_confirmed=1 AND g.starts_at>=? AND g.starts_at<?");
 const [year,month]=event.data.month.split('-').map(Number),start=new Date(`${year}-${String(month).padStart(2,'0')}-01T00:00:00+03:00`),next=new Date(`${month===12?year+1:year}-${String(month===12?1:month+1).padStart(2,'0')}-01T00:00:00+03:00`);
 assert.equal(event.data.games,confirmedThisMonth.get('demo-player-0001',start.toISOString(),next.toISOString()).n);
});
test('queued Telegram message has Mini App link and leaves outbox after delivery',async()=>{
 const id='987654321',notificationId=crypto.randomUUID();
 db.prepare('INSERT INTO users(id,name,created_at) VALUES(?,?,?)').run(id,'Тест Telegram',new Date().toISOString());
 db.prepare('INSERT INTO notifications VALUES(?,?,?,?,?,?)').run(notificationId,id,'Новая игра: тест','game_test',new Date().toISOString(),null);
 db.prepare('INSERT INTO bot_outbox(notification_id,user_id,body,link,next_attempt_at) VALUES(?,?,?,?,?)').run(notificationId,id,'Новая игра: тест','game_test',new Date().toISOString());
 const originalFetch=globalThis.fetch;let sent;
 process.env.BOT_TOKEN='test-token';process.env.BOT_USERNAME='TennisGOgo_bot';process.env.APP_URL='https://tennisgo-production.up.railway.app/';
 globalThis.fetch=async(_,options)=>{sent=JSON.parse(options.body);return {status:200,json:async()=>({ok:true})};};
 try{await sendNextBotMessage();assert.equal(sent.chat_id,id);assert.equal(sent.reply_markup.inline_keyboard[0][0].web_app.url,'https://tennisgo-production.up.railway.app/?start=game_test');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM bot_outbox WHERE notification_id=?').get(notificationId).n,0);}
 finally{globalThis.fetch=originalFetch;delete process.env.BOT_TOKEN;delete process.env.BOT_USERNAME;delete process.env.APP_URL;}
 process.env.RAILWAY_PUBLIC_DOMAIN='tennisgo-production.up.railway.app';
 try{assert.equal(notificationButton('training_test').web_app.url,'https://tennisgo-production.up.railway.app/?start=training_test');}
 finally{delete process.env.RAILWAY_PUBLIC_DOMAIN;}
});
test('game and training reminders reach joined members at 12 and 3 hours exactly once',async()=>{
 const startsAt=new Date(Date.now()+13*3600000).toISOString(),baseGame={sport:'tennis',kind:'friendly',seats:2,courtId:'dinamo',startsAt,duration:60,levelMin:2.5,levelMax:4,price:500,opponentGender:'any'};
 const game=(await request('/games','demo-player-0001','POST',baseGame)).data.game;
 assert.equal((await request(`/games/${game.id}/join`,'demo-player-0002','POST')).status,200);
 const training=(await request('/trainings','demo-coach-0004','POST',{sport:'tennis',format:'split',seats:2,courtId:'dinamo',startsAt,duration:60,ntrpMin:null,ntrpMax:null,price:600})).data.training;
 assert.equal((await request(`/trainings/${training.id}/join`,'demo-player-0002','POST')).status,200);
 const at12=new Date(Date.parse(startsAt)-12*3600000),at3=new Date(Date.parse(startsAt)-3*3600000);
 processEventReminders(at12);processEventReminders(at12);
 for(const [kind,id,recipient] of [['game',game.id,'demo-player-0002'],['training',training.id,'demo-player-0002'],['training',training.id,'demo-coach-0004']]){
   assert.equal(db.prepare('SELECT COUNT(*) AS n FROM event_reminders WHERE kind=? AND listing_id=? AND user_id=? AND hours_before=12').get(kind,id,recipient).n,1);
 }
 processEventReminders(at3);processEventReminders(at3);
 assert.equal(db.prepare('SELECT COUNT(*) AS n FROM event_reminders WHERE listing_id=? AND user_id=?').get(game.id,'demo-player-0002').n,2);
 assert.equal(db.prepare('SELECT COUNT(*) AS n FROM event_reminders WHERE listing_id=? AND user_id=?').get(training.id,'demo-player-0002').n,2);
 assert.ok((await request('/notifications','demo-player-0002')).data.items.some(n=>n.body.includes('через 3 ч')));
});
test('catalog exposes cached court coordinates without storing the player location',async()=>{
 db.prepare('INSERT INTO court_geocodes VALUES(?,?,?,?)').run('краснодар, ул. красная, 190',45.0401,38.9766,new Date().toISOString());
 const result=await request('/catalog','demo-player-0002');
 assert.equal(result.status,200);
 assert.deepEqual(result.data.courts.filter(c=>c.sport==='tennis').slice(0,14).map(c=>c.id),['alfa-tennis','sport-park','dinamo','tennis-park-arena','zhk-luchshiy','trud','setbol','damani','vopreki-tennis','sport-city','indoor-skobeleva','kubgau','zhk-dostoyanie','cska-tennis']);
 const court=result.data.courts.find(c=>c.id==='dinamo');
 assert.equal(court.latitude,45.0401);assert.equal(court.longitude,38.9766);
 assert.equal(result.data.courts.find(c=>c.id==='padel360').latitude,null);
});
test.after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();fs.rmSync(dir,{recursive:true,force:true});});

test('administrator retains player and coach functions, moderates content and sees activity',async()=>{
 process.env.ADMIN_DEMO_USER_ID='demo-admin-0009';
 const admin='demo-admin-0009',player='demo-player-0003';
 assert.equal((await request('/admin/stats',player)).status,403);
 assert.equal((await request('/admin/messages',player)).status,403);
 const stats=await request('/admin/stats',admin);assert.equal(stats.status,200,JSON.stringify(stats.data));assert.ok(stats.data.total>=5);assert.equal(stats.data.daily.length,30);assert.ok(stats.data.activeToday>=1);assert.ok(stats.data.onlineNow>=1);
 const profile=await request('/profile',admin,'POST',{...registration('Администратор','male'),coachYears:8,coachSports:['tennis','padel']});assert.equal(profile.status,200);assert.equal(profile.data.user.role,'player');assert.equal(profile.data.user.coachYears,8);
 const startsAt=new Date(Date.now()+3*86400000).toISOString();
 const training=await request('/trainings',admin,'POST',{sport:'tennis',format:'individual',seats:1,courtId:'dinamo',startsAt,duration:60,ntrpMin:null,ntrpMax:null,price:1000,note:'Урок'});assert.equal(training.status,201,JSON.stringify(training.data));
 const ownClub=await request('/admin/clubs',admin,'POST',{clubName:'Корт Админа',clubAddress:'ул. Красная, 10',city:'Краснодар',clubPhone:'+7 900 123-45-67',clubSports:['tennis'],clubPhotoData:coachPhoto,clubSurface:'clay',opensAt:'08:00',closesAt:'22:00',hourlyPrice:900});assert.equal(ownClub.status,201,JSON.stringify(ownClub.data));
 assert.equal((await request('/me',admin)).data.user.role,'player');
 assert.equal((await request('/me',admin)).data.user.club.status,'approved');
 assert.equal((await request('/admin/clubs/'+admin+'/calendar?date='+new Date().toISOString().slice(0,10),admin)).status,200);
 assert.equal((await request('/admin/clubs/'+admin,admin,'PATCH',{clubName:'Корт Админа',clubAddress:'ул. Красная, 11',city:'Краснодар',clubPhone:'+7 900 123-45-67',clubSports:['tennis'],clubPhotoData:coachPhoto,clubSurface:'clay',opensAt:'08:00',closesAt:'22:00',hourlyPrice:1000})).status,200);
 const game=await request('/games',player,'POST',{sport:'tennis',kind:'friendly',seats:2,courtId:'dinamo',startsAt,duration:60,levelMin:1,levelMax:7,price:0,opponentGender:'any'});assert.equal(game.status,201);
 assert.equal((await request('/admin/listings',admin)).data.games.some(g=>g.id===game.data.game.id),true);
 assert.equal((await request('/games/'+game.data.game.id,admin,'DELETE')).status,200);
 assert.equal((await request('/trainings/'+training.data.training.id,admin,'DELETE')).status,200);
 const direct=await request('/direct/'+player,admin,'POST',{message:'Тест модерации'});assert.equal(direct.status,200,JSON.stringify(direct.data));
 const messages=await request('/admin/messages',admin);assert.equal(messages.status,200);const message=messages.data.messages.find(m=>m.body==='Тест модерации');assert.ok(message);
 assert.equal((await request('/admin/messages/direct/'+message.id,player,'DELETE')).status,403);
 assert.equal((await request('/admin/messages/direct/'+message.id,admin,'DELETE')).status,200);
 assert.ok(!(await request('/direct/'+player,admin)).data.messages.some(m=>m.id===message.id));
 assert.equal((await request('/admin/users/'+player+'/block',admin,'POST',{reason:'Нарушение правил'})).status,200);
 assert.equal((await request('/me',player)).data.user.blockedAt!==null,true);
 assert.equal((await request('/games',player)).status,403);
 assert.equal((await request('/admin/users/'+admin+'/block',admin,'POST',{reason:'Нельзя'})).status,403);
 assert.equal((await request('/admin/users/'+player+'/unblock',admin,'POST')).status,200);
 assert.equal((await request('/games',player)).status,200);
 assert.ok(db.prepare("SELECT 1 FROM moderation_actions WHERE action='delete' AND target_kind='direct_message' AND target_id=?").get(message.id));
});

test('post-match votes count only reciprocal answers',async()=>{
 const make=async(seats=2)=>{
   const made=await request('/games','demo-player-0001','POST',{sport:'tennis',kind:'rating',seats,courtId:'dinamo',startsAt:new Date(Date.now()+86400000).toISOString(),duration:60,levelMin:1,levelMax:7,price:0,opponentGender:'any'});
   assert.equal(made.status,201,JSON.stringify(made.data));const id=made.data.game.id;
   for(const user of (seats===4?['demo-player-0002','demo-player-0003','demo-coach-0004']:['demo-player-0002']))assert.equal((await request('/games/'+id+'/join',user,'POST')).status,200);
   db.prepare('UPDATE games SET starts_at=? WHERE id=?').run(new Date(Date.now()-2*3600000).toISOString(),id);
   processMatchPrompts();processMatchPrompts();
   assert.equal(db.prepare('SELECT COUNT(*) AS n FROM match_polls WHERE game_id=?').get(id).n,1);
   assert.equal(db.prepare('SELECT COUNT(*) AS n FROM notifications WHERE link=? AND body LIKE ?').get('game_'+id,'Укажите результат%').n,seats);
   return id;
 };
 const before=(await request('/me','demo-player-0001')).data.user.ratings.tennis.matches;
 const missing=await make();
 assert.equal((await request('/match-polls','demo-player-0002')).data.games.some(g=>g.id===missing),true);
 assert.equal((await request('/games/'+missing+'/vote','demo-player-0001','POST',{choice:'win'})).status,200);
 assert.equal((await request('/games/'+missing+'/vote','demo-player-0001','POST',{choice:'loss'})).status,409);
 assert.equal((await request('/match-polls','demo-player-0001')).data.games.some(g=>g.id===missing),false);
 assert.equal((await request('/me','demo-player-0001')).data.user.ratings.tennis.matches,before);
 assert.equal((await request('/games/'+missing+'/vote','demo-player-0002','POST',{choice:'loss'})).status,200);
 assert.equal((await request('/games/'+missing,'demo-player-0001')).data.game.resultConfirmed,true);
 assert.equal((await request('/me','demo-player-0001')).data.user.ratings.tennis.matches,before+1);
 const conflict=await make();
 for(const user of ['demo-player-0001','demo-player-0002'])assert.equal((await request('/games/'+conflict+'/vote',user,'POST',{choice:'win'})).status,200);
 assert.equal((await request('/games/'+conflict,'demo-player-0001')).data.game.voteStatus,'not_counted');
 const noScore=await make();
 for(const user of ['demo-player-0001','demo-player-0002'])assert.equal((await request('/games/'+noScore+'/vote',user,'POST',{choice:'no_score'})).status,200);
 assert.equal((await request('/games/'+noScore,'demo-player-0001')).data.game.voteStatus,'not_counted');
 assert.equal((await request('/me','demo-player-0001')).data.user.ratings.tennis.matches,before+1);
 const doubles=await make(4);
 for(const [user,choice] of [['demo-player-0001','win'],['demo-player-0002','loss'],['demo-player-0003','win']])assert.equal((await request('/games/'+doubles+'/vote',user,'POST',{choice})).status,200);
 assert.equal((await request('/games/'+doubles,'demo-player-0001')).data.game.resultConfirmed,false);
 assert.equal((await request('/games/'+doubles+'/vote','demo-coach-0004','POST',{choice:'loss'})).status,200);
 assert.equal((await request('/games/'+doubles,'demo-player-0001')).data.game.voteStatus,'confirmed');
 assert.equal((await request('/me','demo-player-0001')).data.user.ratings.tennis.matches,before+2);
});

test('Telegram result buttons belong to the participant and use the same vote record',async()=>{
 const numeric='7788990011',id=crypto.randomUUID();
 db.prepare('INSERT INTO users(id,name,created_at,registration_version,role,gender,ntrp_level) VALUES(?,?,?,?,?,?,?)').run(numeric,'Игрок Telegram',new Date().toISOString(),2,'player','male',3);
 const made=await request('/games','demo-player-0001','POST',{sport:'tennis',kind:'rating',seats:2,courtId:'dinamo',startsAt:new Date(Date.now()+86400000).toISOString(),duration:60,levelMin:1,levelMax:7,price:0,opponentGender:'any'});
 assert.equal(made.status,201);
 const gameId=made.data.game.id;
 db.prepare('INSERT INTO participants VALUES(?,?,?)').run(gameId,numeric,new Date().toISOString());
 db.prepare('UPDATE games SET starts_at=? WHERE id=?').run(new Date(Date.now()-2*3600000).toISOString(),gameId);
 process.env.BOT_TOKEN='test-token';
 const fetchBefore=globalThis.fetch,methods=[];
 globalThis.fetch=async(url,options)=>{methods.push({url:String(url),payload:JSON.parse(options.body)});return {status:200,json:async()=>({ok:true,result:true})};};
 try{
   processMatchPrompts();
   const item=db.prepare('SELECT * FROM bot_outbox WHERE user_id=? AND link=? AND body LIKE ?').get(numeric,'game_'+gameId,'Укажите результат%');
   assert.ok(item);
   assert.equal(JSON.parse(item.reply_markup).inline_keyboard[0][0].callback_data,'rv:'+gameId+':win');
   await sendNextBotMessage();
   assert.ok(methods.some(m=>m.url.endsWith('/sendMessage')&&m.payload.reply_markup.inline_keyboard[2][0].callback_data==='rv:'+gameId+':no_score'));
   await handleBotUpdate({callback_query:{id:'cb-one',data:'rv:'+gameId+':loss',from:{id:Number(numeric)},message:{chat:{id:Number(numeric)},message_id:42}}});
   assert.equal(db.prepare('SELECT choice FROM match_votes WHERE game_id=? AND user_id=?').get(gameId,numeric).choice,'loss');
   await handleBotUpdate({callback_query:{id:'cb-other',data:'rv:'+gameId+':win',from:{id:1234},message:{chat:{id:1234},message_id:42}}});
   assert.equal(db.prepare('SELECT COUNT(*) AS n FROM match_votes WHERE game_id=?').get(gameId).n,1);
   assert.ok(methods.some(m=>m.url.endsWith('/answerCallbackQuery')));
 }finally{globalThis.fetch=fetchBefore;delete process.env.BOT_TOKEN;}
 assert.equal((await request('/games/'+gameId+'/vote','demo-player-0001','POST',{choice:'win'})).status,200);
 assert.equal((await request('/games/'+gameId,'demo-player-0001')).data.game.voteStatus,'confirmed');
});

test('game court status is explicit and profile gallery media persists on the volume',async()=>{
 const owner='demo-media-0010',visitor='demo-player-0002';
 assert.equal((await request('/profile',owner,'POST',{...registration('Тренер Елена','female','coach'),coachSports:['tennis']})).status,200);
 const startsAt=new Date(Date.now()+3*86400000).toISOString(),baseGame={sport:'tennis',kind:'friendly',seats:2,courtId:'dinamo',startsAt,duration:60,levelMin:2,levelMax:4,price:500,note:''};
 const pending=await request('/games',owner,'POST',baseGame);assert.equal(pending.status,201);assert.equal(pending.data.game.courtReserved,false);
 const confirmed=await request('/games',owner,'POST',{...baseGame,courtReserved:true});assert.equal(confirmed.status,201);assert.equal(confirmed.data.game.courtReserved,true);
 assert.equal((await request(`/games/${pending.data.game.id}`,visitor,'PATCH',{...baseGame,courtReserved:true,opponentGender:'any'})).status,403);
 const edited=await request(`/games/${pending.data.game.id}`,owner,'PATCH',{...baseGame,courtReserved:true,opponentGender:'any'});assert.equal(edited.status,200);assert.equal(edited.data.game.courtReserved,true);
 assert.equal((await request('/games',owner,'POST',{...baseGame,courtReserved:'yes'})).status,400);
 const jpeg=Buffer.concat([Buffer.from([0xff,0xd8]),Buffer.alloc(16),Buffer.from([0xff,0xd9])]);
 const photo=await request('/profile/media',owner,'POST',{kind:'photo',data:'data:image/jpeg;base64,'+jpeg.toString('base64')});assert.equal(photo.status,201);
 const mp4=Buffer.concat([Buffer.alloc(4),Buffer.from('ftyp'),Buffer.alloc(12)]);
 const video=await request('/profile/media',owner,'POST',{kind:'video',data:'data:video/mp4;base64,'+mp4.toString('base64')});assert.equal(video.status,201);
 const gallery=await request(`/users/${owner}/media`,visitor);assert.equal(gallery.status,200);assert.equal(gallery.data.items.length,2);
 const response=await fetch(base+video.data.item.url,{headers:{Range:'bytes=0-7'}});assert.equal(response.status,206);assert.equal(response.headers.get('content-type'),'video/mp4');assert.equal((await response.arrayBuffer()).byteLength,8);
 assert.equal((await request('/profile/media/'+photo.data.item.id,visitor,'DELETE')).status,403);
 assert.equal((await request('/profile/media/'+photo.data.item.id,owner,'DELETE')).status,200);
 assert.equal((await request(`/users/${owner}/media`,visitor)).data.items.length,1);
 assert.equal((await fetch(base+photo.data.item.url)).status,404);
});

test('player training requests notify local coaches and, for split or group, local players',async()=>{
 const owner='demo-training-seeker-0011',coach='demo-request-coach-0012',player='demo-request-player-0013',padelOnly='demo-request-padel-0014',away='demo-request-away-0015';
 assert.equal((await request('/profile',owner,'POST',{...registration('Ищу тренировку','female'),city:'Краснодар'})).status,200);
 assert.equal((await request('/profile',coach,'POST',{...registration('Тренер','male','coach'),city:'Краснодар',coachSports:['tennis']})).status,200);
 assert.equal((await request('/profile',player,'POST',{...registration('Партнёр','male'),city:'Краснодар'})).status,200);
 assert.equal((await request('/profile',padelOnly,'POST',{...registration('Только падел','male'),city:'Краснодар'})).status,200);
 assert.equal((await request('/preferences/sports',padelOnly,'PATCH',{sports:['padel']})).status,200);
 assert.equal((await request('/profile',away,'POST',{...registration('В другом городе','male','coach'),city:'Анапа',coachSports:['tennis']})).status,200);
 const startsAt=new Date(Date.now()+4*86400000);startsAt.setUTCHours(15,0,0,0);
 const payload={sport:'tennis',format:'individual',courtIds:['alfa-tennis','dinamo'],startsAt:startsAt.toISOString(),endsAt:new Date(startsAt.getTime()+2*3600000).toISOString(),note:'Нужна подача'};
 const before=(id)=>(db.prepare("SELECT COUNT(*) AS n FROM notifications WHERE user_id=? AND link LIKE 'training_request_%'").get(id).n);
 const initial=[coach,player,padelOnly,away].map(before);
 const created=await request('/training-requests',owner,'POST',payload);assert.equal(created.status,201);
 const id=created.data.request.id;assert.equal(created.data.request.courts.length,2);assert.equal(created.data.request.playerName,'Ищу т.');
 assert.equal(before(coach),initial[0]+1);assert.equal(before(player),initial[1]);assert.equal(before(padelOnly),initial[2]);assert.equal(before(away),initial[3]);
 assert.equal(db.prepare('SELECT link FROM notifications WHERE user_id=? AND link=?').get(coach,'training_request_'+id).link,'training_request_'+id);
 assert.equal((await request('/training-requests',player)).data.requests.some(r=>r.id===id),false);
 assert.equal((await request(`/training-requests/${id}`,player)).status,403);
 assert.equal((await request('/training-requests',coach,'POST',payload)).status,403);
 assert.equal((await request('/training-requests',owner,'POST',{...payload,courtIds:['dinamo','dinamo']})).status,400);
 assert.equal((await request('/training-requests',owner,'POST',{...payload,sport:'padel'})).status,400);
 assert.equal((await request('/training-requests',owner,'POST',{...payload,endsAt:new Date(startsAt.getTime()-3600000).toISOString()})).status,400);
 const group=await request('/training-requests',owner,'POST',{...payload,format:'group',seats:4});assert.equal(group.status,201);
 assert.equal((await request('/training-requests',player)).data.requests.some(r=>r.id===group.data.request.id),true);
 assert.equal((await request(`/training-requests/${group.data.request.id}`,player)).data.request.seats,4);
 assert.equal(before(coach),initial[0]+2);assert.equal(before(player),initial[1]+1);assert.equal(before(padelOnly),initial[2]);
 assert.equal((await request(`/training-requests/${id}`,player,'DELETE')).status,403);
 assert.equal((await request(`/training-requests/${id}`,owner,'DELETE')).status,200);
 assert.equal((await request(`/training-requests/${id}`,coach)).status,404);
 assert.equal((await request('/training-requests',owner)).data.requests.some(r=>r.id===id),false);
});

test('today starts at the next full Moscow hour and profile roles can change both ways',async()=>{
 assert.equal(new Date(earliestStart(Date.parse('2026-09-28T21:05:00Z'))).toISOString(),'2026-09-28T22:00:00.000Z');
 assert.equal(new Date(earliestStart(Date.parse('2026-09-28T20:59:00Z'))).toISOString(),'2026-09-28T21:00:00.000Z');
 const player='demo-switch-player-0001',coach='demo-switch-coach-0001';
 assert.equal((await request('/profile',player,'POST',registration('Игрок','female'))).status,200);
 assert.equal((await request('/profile',player,'POST',{...registration('Новый тренер','female','coach'),coachSports:['tennis'],coachYears:4})).data.user.role,'coach');
 assert.equal((await request('/profile',coach,'POST',{...registration('Тренер','male','coach'),coachSports:['tennis']})).status,200);
 assert.equal((await request('/profile',coach,'POST',{...registration('Новый игрок','male'),ntrpLevel:2.5})).data.user.role,'player');
 const start=new Date(earliestStart()+3600000).toISOString(),early=new Date(earliestStart()-3600000).toISOString();
 const game={sport:'tennis',kind:'friendly',seats:2,courtId:'dinamo',duration:60,levelMin:2,levelMax:4,price:1000,note:'',startsAt:start};
 assert.equal((await request('/games',coach,'POST',{...game,startsAt:early})).status,400);
 assert.equal((await request('/games',coach,'POST',game)).status,201);
 assert.equal((await request('/trainings',player,'POST',{sport:'tennis',format:'individual',seats:1,courtId:'dinamo',startsAt:early,duration:60,ntrpMin:null,ntrpMax:null,price:1000,note:''})).status,400);
});

test('one coach accepts player request, creates training with enrolled player and keeps own calendar',async()=>{
 const player='demo-request-owner-0011',coach='demo-request-coach-0011',other='demo-request-coach-0012';
 await request('/profile',player,'POST',registration('Ирина','female'));
 for(const [id,name] of [[coach,'Первый'],[other,'Второй']])await request('/profile',id,'POST',{...registration(name,'male','coach'),coachSports:['tennis']});
 const startsAt=new Date(earliestStart()+4*3600000).toISOString(),endsAt=new Date(Date.parse(startsAt)+3*3600000).toISOString();
 const published=await request('/training-requests',player,'POST',{sport:'tennis',format:'group',seats:3,courtIds:['dinamo'],startsAt,endsAt,note:'Группа'});
 assert.equal(published.status,201);
 const id=published.data.request.id,chosen=new Date(Date.parse(startsAt)+3600000).toISOString();
 assert.ok((await request('/training-requests',coach)).data.requests.some(r=>r.id===id));
 assert.equal((await request(`/training-requests/${id}/accept`,player,'POST',{courtId:'dinamo',startsAt:chosen,duration:60,seats:3,price:1500})).status,403);
 assert.equal((await request(`/training-requests/${id}/accept`,coach,'POST',{courtId:'alfa-tennis',startsAt:chosen,duration:60,seats:3,price:1500})).status,400);
 const accepted=await request(`/training-requests/${id}/accept`,coach,'POST',{courtId:'dinamo',startsAt:chosen,duration:60,seats:3,price:1500});
 assert.equal(accepted.status,201);assert.equal(accepted.data.training.members[0].id,player);assert.equal(accepted.data.training.price,1500);
 assert.equal((await request(`/training-requests/${id}/accept`,other,'POST',{courtId:'dinamo',startsAt:chosen,duration:60,seats:3,price:1600})).status,409);
 assert.equal((await request(`/training-requests/${id}`,other)).status,404);
 assert.ok(!(await request('/training-requests',coach)).data.requests.some(r=>r.id===id));
 assert.ok((await request('/trainings',coach)).data.trainings.some(t=>t.id===accepted.data.training.id));
 assert.ok(!(await request('/trainings',other)).data.trainings.some(t=>t.id===accepted.data.training.id));
 assert.equal((await request('/trainings',player)).data.trainings.find(t=>t.id===accepted.data.training.id).price,1500);
 assert.ok((await request('/notifications',player)).data.items.some(n=>n.body.includes('подтвердил вашу тренировку')));
});

test('players join split and group requests; the coach carries every participant into training',async()=>{
 const owner='demo-group-owner-0021',first='demo-group-first-0022',second='demo-group-second-0023',extra='demo-group-extra-0024',coach='demo-group-coach-0025',away='demo-group-away-0026';
 for(const [id,name] of [[owner,'Автор'],[first,'Первый'],[second,'Второй'],[extra,'Четвёртый']])assert.equal((await request('/profile',id,'POST',registration(name,'male'))).status,200);
 assert.equal((await request('/profile',coach,'POST',{...registration('Тренер','female','coach'),coachSports:['tennis']})).status,200);
 assert.equal((await request('/profile',away,'POST',{...registration('Из другого города','female'),city:'Анапа'})).status,200);
 const startsAt=new Date(earliestStart()+8*3600000).toISOString(),endsAt=new Date(Date.parse(startsAt)+3*3600000).toISOString();
 const base={sport:'tennis',courtIds:['dinamo'],startsAt,endsAt,note:'Собираем компанию'};
 const split=(await request('/training-requests',owner,'POST',{...base,format:'split'})).data.request;
 assert.equal(split.seats,2);assert.equal(split.members.length,1);
 assert.equal((await request(`/training-requests/${split.id}/join`,coach,'POST')).status,403);
 assert.equal((await request(`/training-requests/${split.id}/join`,owner,'POST')).status,409);
 assert.equal((await request(`/training-requests/${split.id}/join`,away,'POST')).status,200);
 assert.equal((await request(`/training-requests/${split.id}/leave`,away,'POST')).status,200);
 assert.equal((await request(`/training-requests/${split.id}/join`,first,'POST')).status,200);
 assert.equal((await request(`/training-requests/${split.id}/join`,second,'POST')).status,409);
 const listed=(await request('/training-requests',second)).data.requests.find(r=>r.id===split.id);
 assert.deepEqual(listed.members.map(m=>m.id),[owner,first]);assert.equal(listed.joined,false);
 assert.equal((await request(`/training-requests/${split.id}/leave`,first,'POST')).status,200);
 assert.equal((await request(`/training-requests/${split.id}/join`,second,'POST')).status,200);
 assert.equal((await request(`/training-requests/${split.id}/leave`,first,'POST')).status,409);
 const group=await request('/training-requests',owner,'POST',{...base,format:'group',seats:3});assert.equal(group.status,201);
 const id=group.data.request.id;
 assert.equal((await request(`/training-requests/${id}/join`,first,'POST')).status,200);
 assert.equal((await request(`/training-requests/${id}/join`,second,'POST')).status,200);
 assert.equal((await request(`/training-requests/${id}/join`,extra,'POST')).status,409);
 const detail=(await request(`/training-requests/${id}`,extra)).data.request;
 assert.equal(detail.members.length,3);assert.deepEqual(detail.members.map(m=>m.name),['Автор Т.','Первый Т.','Второй Т.']);
 const chosen=new Date(Date.parse(startsAt)+3600000).toISOString();
 assert.equal((await request(`/training-requests/${id}/accept`,coach,'POST',{courtId:'dinamo',startsAt:chosen,duration:60,seats:3,price:1200})).status,201);
 const accepted=(await request('/trainings',first)).data.trainings.find(t=>t.members.some(m=>m.id===second)&&t.coachId===coach);
 assert.ok(accepted);assert.deepEqual(accepted.members.map(m=>m.id).sort(),[owner,first,second].sort());
 assert.equal((await request(`/training-requests/${id}/join`,extra,'POST')).status,409);
 assert.equal((await request('/notifications',first)).data.items.some(n=>n.body.includes('подтвердил вашу тренировку')),true);
});

test('private repeated games and trainings require friendship, preserve private contact and expose presence',async()=>{
 const owner='demo-private-owner-0041',friend='demo-private-friend-0042',stranger='demo-private-other-0043',coach='demo-private-coach-0044';
 assert.equal((await request('/profile',owner,'POST',{...registration('Одно','male'),name:'Одно'})).status,400);
 assert.equal((await request('/profile',owner,'POST',{...registration('Владелец Игрок','male'),phone:''})).status,400);
 assert.equal((await request('/profile',coach,'POST',{...registration('Мария Тренер','female','coach'),telegramContact:''})).status,400);
 for(const [id,name,role] of [[owner,'Владелец Игрок','player'],[friend,'Друг Игрок','player'],[stranger,'Гость Игрок','player'],[coach,'Мария Тренер','coach']])assert.equal((await request('/profile',id,'POST',{...registration(name,role==='coach'?'female':'male',role),coachSports:['tennis']})).status,200);
 const profile=(await request('/users/'+owner,stranger)).data.user;
 assert.equal(profile.name,'Владелец И.');assert.equal(profile.phone,null);assert.equal(profile.telegramContact,null);assert.equal(typeof profile.online,'boolean');
 const coachProfile=(await request('/users/'+coach,stranger)).data.user;assert.equal(coachProfile.phone,'+7 999 123-45-67');assert.equal(coachProfile.telegramContact,'coach_test');
 assert.equal((await request('/friends/'+friend,owner,'POST')).status,201);
 assert.equal((await request('/friends',friend)).data.incoming[0].id,owner);
 assert.equal((await request('/friends/'+owner+'/accept',friend,'POST')).status,200);
 assert.equal((await request('/friends',owner)).data.accepted[0].id,friend);
 const startsAt=new Date(earliestStart()+6*3600000).toISOString();
 const gamePayload={sport:'tennis',kind:'friendly',seats:2,courtId:'dinamo',startsAt,duration:60,levelMin:2,levelMax:4,price:0,note:'Друзья',friendsOnly:true,repeat:true};
 const game=await request('/games',owner,'POST',gamePayload);assert.equal(game.status,201);assert.equal(game.data.created,5);assert.equal(game.data.game.friendsOnly,true);
 assert.equal(db.prepare('SELECT COUNT(*) AS n FROM games WHERE series_id=?').get(game.data.game.id).n,5);
 const gameStarts=db.prepare('SELECT starts_at FROM games WHERE series_id=? ORDER BY starts_at').all(game.data.game.id).map(x=>Date.parse(x.starts_at));assert.deepEqual(gameStarts.slice(1).map((t,i)=>(t-gameStarts[i])/86400000),[7,7,7,7]);
 assert.equal((await request('/games',friend)).data.games.filter(g=>g.seriesId===game.data.game.id).length,5);
 assert.equal((await request('/games',stranger)).data.games.some(g=>g.id===game.data.game.id),false);
 assert.equal((await request('/games/'+game.data.game.id,stranger)).status,404);
 assert.equal((await request('/games/'+game.data.game.id+'/join',stranger,'POST')).status,404);
 assert.equal((await request('/games/'+game.data.game.id+'/join',friend,'POST')).status,200);
 assert.equal((await request('/friends/'+owner,friend,'DELETE')).status,200);
 assert.equal((await request('/games/'+game.data.game.id,friend)).status,200);
 assert.equal((await request('/games/'+game.data.game.id+'/join',stranger,'POST')).status,404);
 assert.equal((await request('/friends/'+friend,coach,'POST')).status,201);
 assert.equal((await request('/friends/'+coach+'/accept',friend,'POST')).status,200);
 const trainingPayload={sport:'tennis',format:'split',seats:2,courtId:'dinamo',startsAt,duration:60,ntrpMin:null,ntrpMax:null,price:1000,note:'Для друзей',friendsOnly:true,repeat:true};
 const training=await request('/trainings',coach,'POST',trainingPayload);assert.equal(training.status,201);assert.equal(training.data.created,5);
 const trainingId=training.data.training.id;
 const trainingStarts=db.prepare('SELECT starts_at FROM trainings WHERE series_id=? ORDER BY starts_at').all(trainingId).map(x=>Date.parse(x.starts_at));assert.deepEqual(trainingStarts.slice(1).map((t,i)=>(t-trainingStarts[i])/86400000),[7,7,7,7]);
 assert.equal((await request('/trainings',friend)).data.trainings.filter(t=>t.seriesId===trainingId).length,5);
 assert.equal((await request('/trainings',stranger)).data.trainings.some(t=>t.id===trainingId),false);
 assert.equal((await request('/trainings/'+trainingId,stranger)).status,404);
 assert.equal((await request('/trainings/'+trainingId+'/join',stranger,'POST')).status,404);
 assert.equal((await request('/trainings/'+trainingId+'/join',friend,'POST')).status,200);
 db.prepare('UPDATE users SET last_seen_at=? WHERE id=?').run(new Date(Date.now()-180000).toISOString(),owner);
 assert.equal((await request('/users/'+owner,stranger)).data.user.online,false);
 assert.equal((await request('/presence',stranger)).status,404);
 assert.equal((await request('/users?role=coach',stranger)).data.users.some(u=>u.id===coach),true);
});

test('bot advertises vacancies once per interval and trainer confirms signup from Telegram',async()=>{
 const player='731001001',coach='731001002',start=new Date(earliestStart()+12*3600000).toISOString(),id=crypto.randomUUID();
 for(const [userId,role] of [[player,'player'],[coach,'coach']])db.prepare('INSERT INTO users(id,name,username,created_at,role,gender,ntrp_level,registered_at,registration_version,city,coach_sports) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(userId,userId,'',new Date().toISOString(),role,'male',role==='player'?3:null,new Date().toISOString(),2,'Краснодар',role==='coach'?'["tennis"]':'[]');
 db.prepare('INSERT INTO trainings(id,coach_id,sport,format,seats,court_id,starts_at,duration,avg_ntrp,price,note,created_at,ntrp_min,ntrp_max,requires_approval) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,coach,'tennis','group',4,'dinamo',start,90,null,1800,'Группа',new Date().toISOString(),null,null,1);
 const previousToken=process.env.BOT_TOKEN,previousFetch=globalThis.fetch;process.env.BOT_TOKEN='test-token';
 globalThis.fetch=async url=>{if(String(url).includes('api.telegram.org'))return {ok:true,json:async()=>({ok:true,result:true})};return previousFetch(url);};
 try{
  const reference=new Date();processTrainingAds(reference);processTrainingAds(new Date(reference.getTime()+3600000));
  let ads=db.prepare('SELECT * FROM training_ads WHERE training_id=? AND user_id=?').all(id,player);assert.equal(ads.length,1);
  const advertised=db.prepare('SELECT body,reply_markup AS markup FROM bot_outbox WHERE user_id=? AND link=? ORDER BY rowid DESC LIMIT 1').get(player,`training_${id}`);
  assert.ok(advertised.body.includes('1800 ₽/чел.')&&advertised.body.includes('свободно 4 из 4')&&advertised.body.includes('Красная, 190'));
  assert.equal(JSON.parse(advertised.markup).inline_keyboard[0][0].callback_data,`tj:${id}`);
  await handleBotUpdate({callback_query:{id:'signup',data:`tj:${id}`,from:{id:Number(player)},message:{chat:{id:Number(player)},message_id:1}}});
  assert.equal(db.prepare("SELECT status FROM join_requests WHERE kind='training' AND listing_id=? AND user_id=?").get(id,player).status,'pending');
  const approval=db.prepare('SELECT reply_markup AS markup FROM bot_outbox WHERE user_id=? ORDER BY rowid DESC LIMIT 1').get(coach);
  assert.equal(JSON.parse(approval.markup).inline_keyboard[0][0].callback_data,`ta:${id}:${player}`);
  await handleBotUpdate({callback_query:{id:'approve',data:`ta:${id}:${player}`,from:{id:Number(coach)},message:{chat:{id:Number(coach)},message_id:2}}});
  assert.ok(db.prepare('SELECT 1 FROM training_participants WHERE training_id=? AND user_id=?').get(id,player));
  assert.ok(db.prepare('SELECT body FROM notifications WHERE user_id=? ORDER BY rowid DESC LIMIT 1').get(player).body.includes('подтвердил вашу запись'));
  processTrainingAds(new Date(Date.parse(start)-2*3600000));
  ads=db.prepare('SELECT * FROM training_ads WHERE training_id=? AND user_id=?').all(id,player);assert.equal(ads.length,1);
 }finally{globalThis.fetch=previousFetch;if(previousToken===undefined)delete process.env.BOT_TOKEN;else process.env.BOT_TOKEN=previousToken;}
});


test('post-game scores update reputation and game average without duplicate votes',async()=>{
 const ids=['demo-reputation-001','demo-reputation-002','demo-reputation-003'],gameId=crypto.randomUUID(),started=new Date(Date.now()-5*3600000).toISOString();
 for(const id of ids)db.prepare("INSERT INTO users(id,name,username,created_at,role,gender,ntrp_level,registered_at,registration_version,city) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,id,'',started,'player','male',3,started,2,'Краснодар');
 db.prepare('INSERT INTO games(id,sport,city,venue,court_id,starts_at,duration,level_min,level_max,seats,price,kind,note,creator_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(gameId,'tennis','Краснодар','Динамо','dinamo',started,60,2,4,4,100,'friendly','',ids[0],started);
 for(const id of ids)db.prepare('INSERT INTO participants(game_id,user_id,joined_at) VALUES(?,?,?)').run(gameId,id,started);
 assert.equal((await request('/users/'+ids[1],ids[0])).data.user.reputation,5);
 assert.equal((await request('/games/'+gameId+'/reviews',ids[0])).data.finished,true);
 assert.equal((await request('/games/'+gameId+'/reviews',ids[0],'POST',{targetId:ids[0],score:1})).status,400);
 assert.equal((await request('/games/'+gameId+'/reviews',ids[0],'POST',{targetId:ids[1],score:0})).status,400);
 assert.equal((await request('/games/'+gameId+'/reviews',ids[0],'POST',{targetId:ids[1],score:1,comment:'Оппонент не пришёл'})).status,201);
 assert.equal((await request('/games/'+gameId+'/reviews',ids[0],'POST',{targetId:ids[1],score:5})).status,409);
 let user=(await request('/users/'+ids[1],ids[0])).data.user;assert.equal(user.reputation,1);assert.equal(user.reputationCount,1);
 assert.equal((await request('/games/'+gameId,ids[0])).data.game.reputation,3.67);
 assert.equal((await request('/games/'+gameId+'/reviews',ids[2],'POST',{targetId:ids[1],score:5})).status,201);
 user=(await request('/users/'+ids[1],ids[0])).data.user;assert.equal(user.reputation,3);assert.equal(user.reputationCount,2);
 assert.equal((await request('/games/'+gameId,ids[0])).data.game.reputation,4.33);
 assert.equal((await request('/games/'+gameId+'/reviews','demo-player-0001')).status,403);
});
