import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
const temp=mkdtempSync(path.join(tmpdir(),'tennis-rewards-'));
process.env.DB_PATH=path.join(temp,'test.sqlite');delete process.env.BOT_TOKEN;process.env.ADMIN_DEMO_USER_ID='demo-reward-admin';
const bootstrap=new DatabaseSync(process.env.DB_PATH);bootstrap.exec('CREATE TABLE reward_campaign(id TEXT PRIMARY KEY,starts_at TEXT NOT NULL)');bootstrap.prepare('INSERT INTO reward_campaign VALUES(?,?)').run('tennis-go-rewards-v1','2026-01-01T00:00:00.000Z');bootstrap.close();
const {db,server,rewards}=await import('../server.mjs');await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`,admin='demo-reward-admin';
function user(id,role='player',created='2025-01-01T00:00:00.000Z'){db.prepare('INSERT INTO users(id,name,created_at,role,registration_version,registered_at) VALUES(?,?,?,?,2,?)').run(id,id,created,role,created);return id;}
user(admin);const a=user('demo-reward-a'),b=user('demo-reward-b'),c=user('demo-reward-c');
async function api(route,who=a,method='GET',data){const r=await fetch(base+'/api'+route,{method,headers:{'x-demo-user':who,'content-type':'application/json'},body:data?JSON.stringify(data):undefined});return {status:r.status,data:await r.json()};}
function game(players,when,options={}){const id=crypto.randomUUID();db.prepare("INSERT INTO games(id,sport,city,venue,court_id,starts_at,duration,level_min,level_max,seats,price,kind,note,creator_id,created_at,result_confirmed) VALUES(?,'tennis','Краснодар','Корт',?,?,60,2,4,?,0,?,'',?,?,?)").run(id,options.court||'court',when,players.length,options.kind||'friendly',players[0],new Date(Date.parse(when)-86400000).toISOString(),options.confirmed?1:0);for(const idp of players)db.prepare('INSERT INTO participants VALUES(?,?,?)').run(id,idp,new Date(Date.parse(when)-3600000).toISOString());return id;}
function grant(id,amount,source=crypto.randomUUID(),period='2026-09'){db.prepare('INSERT INTO reward_ledger VALUES(?,?,?,?,?,?,?)').run(crypto.randomUUID(),id,'game',source,amount,period,new Date().toISOString());}
const at=d=>`2026-09-${String(d).padStart(2,'0')}T09:00:00.000Z`;
try{
 await test('campaign is seeded once and news embeds a real top 3',async()=>{assert.equal(db.prepare("SELECT COUNT(*) AS n FROM news WHERE id='tennis-go-rewards-v1'").get().n,1);const n=(await api('/news')).data.items.find(x=>x.campaign);assert.ok(n);assert.equal(n.campaign.leaders.length,0);assert.deepEqual(n.campaign.prizes.map(x=>x.remaining),[5,3,3,1]);});
 await test('friendly games require all participants and never duplicate credits',async()=>{const g=game([a,b],at(1));assert.equal((await api('/rewards/proof',c,'POST',{kind:'game',source:g})).status,409);assert.equal((await api('/rewards/proof',a,'POST',{kind:'game',source:g})).status,200);assert.equal(rewards.balance(a).earned,0);await api('/rewards/proof',b,'POST',{kind:'game',source:g});assert.equal(rewards.balance(a).earned,25);await api('/rewards/proof',b,'POST',{kind:'game',source:g});assert.equal(rewards.balance(a).earned,25);const leaders=(await api('/leaderboard?mode=bonus')).data.players;assert.equal(leaders[0].points,25);assert.equal((await api('/news')).data.items.find(x=>x.campaign).campaign.leaders.length,2);});
 await test('repeated opponents, overlaps, retroactive joins and past campaign games are excluded',()=>{game([a,b],at(2),{confirmed:true});rewards.reconcile(true);game([a,b],at(3),{confirmed:true});const overlap=game([a,c],at(2),{confirmed:true});const late=game([a,c],at(4),{confirmed:true});db.prepare('UPDATE participants SET joined_at=? WHERE game_id=? AND user_id=?').run(at(4),late,c);game([a,c],'2025-12-01T09:00:00.000Z',{confirmed:true});rewards.reconcile(true);assert.equal(rewards.balance(a).earned,40);assert.match(db.prepare("SELECT reason FROM reward_checks WHERE user_id=? AND source=?").get(a,overlap).reason,/пересекается/);assert.equal(db.prepare("SELECT COUNT(*) AS n FROM reward_checks WHERE source=?").get(late).n,0);});
 await test('new accounts are held for review and only admin can approve',async()=>{const fresh=user('demo-reward-fresh','player',at(9)),g=game([a,fresh],at(10),{confirmed:true});rewards.reconcile(true);assert.equal(db.prepare('SELECT status FROM reward_checks WHERE user_id=? AND source=?').get(a,g).status,'pending');const payload={action:'check',userId:a,source:g,approved:true,reason:'Проверено посещение корта'};assert.equal((await api('/rewards/admin',a,'POST',payload)).status,403);assert.equal((await api('/rewards/admin',admin,'POST',payload)).status,200);assert.equal((await api('/rewards/admin',admin,'POST',payload)).status,409);assert.equal(rewards.balance(a).earned,65);});
 await test('ordinary points have a shared monthly cap including extra tasks',async()=>{const cap=user('demo-reward-cap'),op=user('demo-reward-cap-op');grant(cap,240);game([cap,op],at(15),{confirmed:true});rewards.reconcile(true);assert.equal(rewards.balance(cap).earned,250);assert.equal(db.prepare("SELECT amount FROM reward_ledger WHERE user_id=? AND task='game' AND source NOT LIKE 'x' ORDER BY amount").all(cap).some(x=>x.amount===10),true);});
 await test('coach rewards need approved partner, actual completion and player confirmation',async()=>{const coach=user('demo-reward-coach','coach'),p=user('demo-reward-trainee'),id=crypto.randomUUID();db.prepare("INSERT INTO trainings(id,coach_id,format,seats,court_id,starts_at,duration,price,note,created_at) VALUES(?,?,'individual',1,'court',?,60,0,'',?)").run(id,coach,at(12),at(11));db.prepare('INSERT INTO training_participants VALUES(?,?,?)').run(id,p,at(11));db.prepare('INSERT INTO completed_trainings VALUES(?,?)').run(id,new Date().toISOString());assert.equal((await api('/rewards/proof',p,'POST',{kind:'training',source:id})).status,409);await api('/rewards/admin',admin,'POST',{action:'partner',userId:coach,approved:true,reason:'Личность тренера проверена'});assert.equal((await api('/rewards/proof',p,'POST',{kind:'training',source:id})).status,200);assert.equal(rewards.balance(p).earned,20);await api('/rewards/proof',p,'POST',{kind:'training',source:id});assert.equal(rewards.balance(p).earned,20);db.prepare('UPDATE trainings SET cancelled_at=? WHERE id=?').run(new Date().toISOString(),id);rewards.reconcile(true);assert.equal(rewards.balance(p).earned,0);});
 await test('court attestation belongs only to the verified representative of that court',async()=>{const owner=user('demo-reward-club','club'),p=user('demo-reward-court-player'),q=user('demo-reward-court-other');db.prepare("INSERT INTO clubs(owner_id,name,address,city,phone,sports,status,created_at) VALUES(?,'Клуб','Адрес','Краснодар','1234567890','[\"tennis\"]','approved',?)").run(owner,at(1));await api('/rewards/admin',admin,'POST',{action:'partner',userId:owner,approved:true,reason:'Клуб проверен'});const id=game([p,q],at(16),{confirmed:true,court:'club-'+owner});assert.equal((await api('/rewards/court',p,'POST',{source:id})).status,403);assert.equal((await api('/rewards/court',owner,'POST',{source:id})).status,200);assert.equal(rewards.balance(p).earned,30);await api('/rewards/court',owner,'POST',{source:id});assert.equal(rewards.balance(p).earned,30);});
 await test('referral requires two real games with different people other than inviter',async()=>{const inviter=user('demo-reward-inviter'),invitee=user('demo-reward-invitee','player',new Date().toISOString()),p=user('demo-reward-ref-op1'),q=user('demo-reward-ref-op2');assert.equal((await api('/rewards/referral',invitee,'POST',{code:inviter})).status,200);assert.equal((await api('/rewards/referral',invitee,'POST',{code:inviter})).status,409);db.prepare('UPDATE reward_referrals SET created_at=? WHERE invitee=?').run(at(16),invitee);game([invitee,p],at(17),{confirmed:true});game([invitee,q],at(18),{confirmed:true});rewards.reconcile(true);const checks=db.prepare("SELECT * FROM reward_checks WHERE user_id=? AND status='pending'").all(invitee);for(const r of checks)await api('/rewards/admin',admin,'POST',{action:'check',userId:invitee,source:r.source,approved:true,reason:'Участие новичка проверено'});rewards.reconcile(true);assert.equal(rewards.balance(inviter).earned,20);rewards.reconcile(true);assert.equal(rewards.balance(inviter).earned,20);});
 await test('concurrent redemptions cannot exceed stock; rejection refunds once without lowering earned total',async()=>{const ids=Array.from({length:6},(_,i)=>user('demo-reward-claim-'+i));for(const id of ids)grant(id,200);const results=await Promise.all(ids.map(id=>api('/rewards/claim',id,'POST',{prize:'balls'})));assert.equal(results.filter(r=>r.status===200).length,5);assert.equal(results.filter(r=>r.status===409).length,1);const index=results.findIndex(r=>r.status===200),id=ids[index],claimId=results[index].data.claimId;assert.deepEqual(rewards.balance(id),{balance:0,earned:200});assert.equal((await api('/rewards/claim',id,'POST',{prize:'balls'})).status,409);const payload={action:'claim',claimId,approved:false,reason:'Неверные данные получения'};assert.equal((await api('/rewards/admin',admin,'POST',payload)).status,200);assert.equal((await api('/rewards/admin',admin,'POST',payload)).status,409);assert.equal(rewards.balance(id).balance,200);assert.equal(rewards.snapshot(id).prizes[0].remaining,1);assert.equal((await api('/rewards/claim',id,'POST',{prize:'racket'})).status,409);});
 await test('cancelled games revoke credited points exactly once',()=>{const p=user('demo-reward-cancel-a'),q=user('demo-reward-cancel-b'),g=game([p,q],at(20),{confirmed:true});rewards.reconcile(true);assert.equal(rewards.balance(p).balance,25);db.prepare('UPDATE games SET cancelled_at=? WHERE id=?').run(new Date().toISOString(),g);rewards.reconcile(true);rewards.reconcile(true);assert.equal(rewards.balance(p).balance,0);assert.equal(rewards.balance(p).earned,0);});
 await test('annual reward is not available on registration and racket cannot be bought manually',async()=>{assert.equal(rewards.annual(a).eligible,false);assert.equal((await api('/rewards/admin',admin,'POST',{action:'annual',userId:a,approved:true,reason:'Проверены годовые условия'})).status,409);assert.equal((await api('/rewards/claim',a,'POST',{prize:'racket'})).status,409);assert.equal((await api('/rewards/admin',admin,'POST',{action:'annual',userId:a,approved:true,reason:''})).status,400);});
 await test('verified year bonus reserves the only racket and revoked annual conditions block issuance',async()=>{
  const RealDate=Date,fixed=RealDate.parse('2027-02-01T12:00:00.000Z');globalThis.Date=class extends RealDate{constructor(...args){super(...(args.length?args:[fixed]));}static now(){return fixed;}};
  try{const p=user('demo-reward-year'),peers=Array.from({length:14},(_,i)=>user('demo-reward-year-op-'+i)),games=[];
    for(let m=1;m<=12;m++){for(let j=0;j<7;j++)games.push(game([p,peers[((m-1)*7+j)%14]],`2026-${String(m).padStart(2,'0')}-${String(2+j*3).padStart(2,'0')}T13:00:00.000Z`,{confirmed:true}));db.prepare('INSERT INTO reward_ledger VALUES(?,?,?,?,?,?,?)').run(crypto.randomUUID(),p,'training','year-visit-'+m,20,`2026-${String(m).padStart(2,'0')}`,new Date().toISOString());}
    grant(p,3000,'year-saving','2026-01');rewards.reconcile(true);assert.equal(rewards.annual(p).eligible,true);
    const awarded=await api('/rewards/admin',admin,'POST',{action:'annual',userId:p,approved:true,reason:'Годовые посещения и встречи проверены'});assert.equal(awarded.status,200,awarded.data.error);
    const claim=db.prepare("SELECT * FROM reward_claims WHERE user_id=? AND prize='racket'").get(p);assert.ok(claim);assert.equal(rewards.snapshot(p).prizes[3].remaining,0);assert.equal(rewards.balance(p).earned-rewards.balance(p).balance,10000);
    assert.equal((await api('/rewards/admin',admin,'POST',{action:'annual',userId:p,approved:true,reason:'Повторная проверка'})).status,409);
    for(const g of games.slice(0,5))db.prepare('UPDATE games SET cancelled_at=? WHERE id=?').run(new Date().toISOString(),g);rewards.reconcile(true);
    assert.equal(rewards.annual(p).eligible,false);assert.ok(rewards.balance(p).balance<0);assert.equal((await api('/rewards/admin',admin,'POST',{action:'claim',claimId:claim.id,approved:true,reason:'Выдать ракетку'})).status,409);
  }finally{globalThis.Date=RealDate;}
 });

}finally{await new Promise(resolve=>server.close(resolve));db.close();rmSync(temp,{recursive:true,force:true});}
