import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

test('offline HTML renders home, games, and create form without a server',async()=>{
 const dir=path.dirname(fileURLToPath(import.meta.url));
 const html=fs.readFileSync(path.join(dir,'../OPEN_DEMO.html'),'utf8');
 const source=html.split('<script>')[1]?.split('</script>')[0];assert.ok(source);
 const handlers={};const app={innerHTML:'',addEventListener(type,fn){(handlers[type]??=[]).push(fn)}};const storage=new Map();
 const context={window:{},document:{querySelector:q=>q==='#app'?app:null},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},crypto,Intl,Date,URLSearchParams,location:{search:'',origin:'file://'},navigator:{},setTimeout,console};
 vm.createContext(context);vm.runInContext(source,context);await new Promise(resolve=>setTimeout(resolve,20));
 assert.ok(app.innerHTML.includes('Добро пожаловать в Tennis GO'));
 assert.ok(app.innerHTML.includes('Я игрок')&&app.innerHTML.includes('Я тренер'));
 assert.ok(app.innerHTML.includes('data-back'));
 vm.runInContext("state.registrationRole='coach';state.registrationStep=2;render()",context);
 assert.ok(app.innerHTML.includes('registration-form')&&app.innerHTML.includes('Мужские')&&app.innerHTML.includes('Женские'));
 assert.ok(app.innerHTML.includes('Расскажите о вашем тренерском опыте'));
 assert.ok(app.innerHTML.includes('name="coachSports" value="tennis"')&&app.innerHTML.includes('name="coachSports" value="padel"'));
 assert.ok(app.innerHTML.includes('name="city"')&&app.innerHTML.includes('Анапа')&&app.innerHTML.includes('name="phone"')&&app.innerHTML.includes('name="telegramContact"'));
 assert.ok(app.innerHTML.includes('id="profile-ntrp-card" hidden'));
 vm.runInContext("state.registrationStep=3;render()",context);assert.ok(app.innerHTML.includes('Тренерский стаж, лет'));
 await vm.runInContext("api('/profile','POST',{name:'Роман',role:'player',gender:'male',playingYears:2,ntrpLevel:3.5,about:'',coachYears:null,photoData:null,avatarId:'male-cap'}).then(()=>refresh()).then(render)",context);
 assert.ok(app.innerHTML.includes('Ближайшие игры')&&app.innerHTML.includes('Стадион «Динамо»'));
 assert.ok(app.innerHTML.includes('Ближайшие тренировки')&&app.innerHTML.includes('compact-training')&&app.innerHTML.includes('стаж 7 лет'));
 assert.ok(app.innerHTML.includes('games-section')&&app.innerHTML.includes('trainings-section'));
 assert.ok(app.innerHTML.includes('СПАРРИНГ')&&app.innerHTML.includes('Тренер - Анастасия')&&app.innerHTML.includes('Сплит · 2 человека · стаж 7 лет'));
 assert.ok(app.innerHTML.includes('ПАРНАЯ'));
 assert.ok(!vm.runInContext('compactGameCard(state.games[0])',context).includes('ПАРНАЯ'));
 assert.ok(vm.runInContext('gameCard(state.games[1])',context).includes('ПАРНАЯ'));
 assert.ok(vm.runInContext('gameDetail(state.games[1])',context).includes('ПАРНАЯ'));
 assert.ok(app.innerHTML.includes('2 места свободно'));
 assert.ok(!app.innerHTML.includes('class="filters"'));
 vm.runInContext("state.filter='tennis';render()",context);
 assert.ok(app.innerHTML.includes('360° Падел'));
 vm.runInContext("state.filter='all';render()",context);
 vm.runInContext("state.games[0].members.push({id:'demo-filled',name:'Игрок'});state.trainings[0].members.push({id:'a',name:'A'},{id:'b',name:'B'});render()",context);
 assert.ok(!app.innerHTML.includes('compact-training')&&!app.innerHTML.includes('Стадион «Динамо»'));
 vm.runInContext("state.games[0].members.pop();state.trainings[0].members=[];render()",context);
 assert.ok(app.innerHTML.includes('Тренировки</button>'));
 assert.ok(!app.innerHTML.includes('data-back'));
 assert.ok(app.innerHTML.includes('class="brand-logo"><img src="data:image/png;base64,'));
 vm.runInContext("state.tab='games'; render()",context);assert.match(app.innerHTML,/Найти игру/);
 vm.runInContext("state.form='create'; render()",context);assert.ok(app.innerHTML.includes('id="create-form"'));assert.ok(app.innerHTML.includes('4 игрока · парная'));assert.ok(app.innerHTML.includes('Академия «Вопреки» — ул. Невкипелого, 24/4'));assert.ok(app.innerHTML.includes('Что означают уровни NTRP 1.0–7.0?'));assert.ok(app.innerHTML.includes('Ракетка для падела'));assert.ok(app.innerHTML.includes('Кто может присоединиться'));
 vm.runInContext("state.form='edit-profile'; render()",context);assert.ok(app.innerHTML.includes('id="profile-form"'));assert.ok(app.innerHTML.includes('Своя фотография'));assert.ok(app.innerHTML.includes('Уровень тенниса · NTRP'));
 assert.ok(app.innerHTML.includes('name="city"')&&app.innerHTML.includes('name="phone"'));
 vm.runInContext("state.form='';state.tab='profile';state.me.role='coach';render()",context);
 assert.ok(app.innerHTML.includes('Создать тренировку'));
 assert.ok(!app.innerHTML.includes('Уровень тенниса · NTRP'));
 vm.runInContext("state.tab='home';render()",context);
 assert.ok(app.innerHTML.includes('class="primary training-action"')&&app.innerHTML.includes('Создать тренировку →'));
 vm.runInContext("state.form='create-training';render()",context);
 assert.ok(app.innerHTML.includes('id="training-form"')&&app.innerHTML.includes('Сплит · 2 человека')&&app.innerHTML.includes('NTRP от')&&app.innerHTML.includes('NTRP до'));
 assert.ok(app.innerHTML.includes('<option value="padel">Падел</option>')&&app.innerHTML.includes('Стадион «Динамо»'));
 vm.runInContext("state.me.coachSports=['padel'];render()",context);
 assert.ok(app.innerHTML.includes('<option value="padel">Падел</option>')&&!app.innerHTML.includes('<option value="tennis">🎾 Теннис</option>'));
 assert.ok(app.innerHTML.includes('360° Падел — ул. Тополиная, 33А'));
 vm.runInContext("state.me.coachSports=['tennis','padel'];render()",context);
 assert.ok(!app.innerHTML.includes('360° Падел — ул. Тополиная, 33А'));
 const courtSelect={innerHTML:''},trainingForm={elements:{courtId:courtSelect}};
 context.trainingSport={name:'sport',value:'padel',form:trainingForm,closest:()=>trainingForm};
 for(const handler of handlers.change)await handler({target:context.trainingSport});
 assert.match(courtSelect.innerHTML,/360° Падел — ул. Тополиная, 33А/);
 assert.ok(app.innerHTML.includes('data-back'));
 vm.runInContext("state.me.role='player';state.form='';render()",context);
 vm.runInContext("state.tab='training';render()",context);
 assert.ok(app.innerHTML.includes('>Тренировки</h1>')&&app.innerHTML.includes('training-gender-filter')&&app.innerHTML.includes('training-format-filter'));
 assert.ok(app.innerHTML.includes('training-sport-filter')&&app.innerHTML.includes('Теннис и падел'));
 vm.runInContext("state.trainingSport='padel';render()",context);assert.ok(app.innerHTML.includes('0 найдено'));
 vm.runInContext("state.trainingSport='tennis';render()",context);assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.trainingSport='all';render()",context);
 assert.ok(app.innerHTML.includes('data-training-court="dinamo"')&&app.innerHTML.includes('data-training-court="padel360"'));
 assert.ok(!app.innerHTML.includes('booking-form')&&!app.innerHTML.includes('Индивидуальная заявка'));
 vm.runInContext("state.trainingGender='male';render()",context);assert.ok(app.innerHTML.includes('0 найдено'));
 vm.runInContext("state.trainingGender='all';state.trainingCourts=['padel360'];render()",context);assert.ok(app.innerHTML.includes('0 найдено'));
 vm.runInContext("state.trainingCourts=['padel360','dinamo'];render()",context);assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.trainingFormat='individual';render()",context);assert.ok(app.innerHTML.includes('0 найдено'));
 vm.runInContext("state.trainingFormat='all';state.trainingGender='all';state.trainingCourts=[];state.trainings[0].members.push({id:'demo-host',name:'Алексей',avatarId:'male-cap'});render()",context);
 assert.ok(app.innerHTML.includes('participant-strip'));
 vm.runInContext('openTraining(state.trainings[0].id)',context);
 assert.ok(app.innerHTML.includes('Записались · 1/2')&&app.innerHTML.includes('data-user="demo-host"'));
 await vm.runInContext("openUser('demo-host')",context);
 assert.ok(app.innerHTML.includes('Профиль участника')&&app.innerHTML.includes('Алексей'));
 vm.runInContext('back()',context);assert.ok(app.innerHTML.includes('Записались · 1/2'));
 vm.runInContext('back()',context);assert.ok(app.innerHTML.includes('>Тренировки</h1>'));
 vm.runInContext('openGame(state.games[0].id)',context);assert.ok(app.innerHTML.includes('data-user="demo-host"'));
 vm.runInContext('back()',context);
 vm.runInContext("state.tab='home';state.history=[];pushView();state.tab='training';render();back()",context);
 assert.ok(app.innerHTML.includes('Ближайшие игры'));
 const boxes={'#level-guide-items':{innerHTML:''},'#court-address':{textContent:''},'#level-summary':{innerHTML:''}};
 const form={elements:{sport:{value:'padel'},seats:{value:'2'},courtId:{value:'padel360',innerHTML:''},levelMin:{value:'2.5',innerHTML:''},levelMax:{value:'3.5',innerHTML:''}},querySelector:q=>boxes[q]};
 context.fakeForm=form;vm.runInContext('updateCreateChoices(fakeForm)',context);
 assert.equal(form.elements.seats.value,'4');
 assert.match(form.elements.courtId.innerHTML,/360° Падел — ул. Тополиная, 33А/);
 assert.doesNotMatch(form.elements.courtId.innerHTML,/Стадион «Динамо»/);
 assert.match(boxes['#level-guide-items'].innerHTML,/Использую стены/);
 form.elements.kind={value:'rating'};vm.runInContext('syncGameFormat(fakeForm)',context);
 assert.equal(form.elements.seats.value,'2');
 vm.runInContext("state.form='';state.tab='games';state.filter='all';state.when='all';state.court='dinamo';state.availableOnly=true;render()",context);
 assert.equal(vm.runInContext('visibleGames({advanced:true}).length',context),1);
 assert.ok(app.innerHTML.includes('1 найдено'));
 assert.match(app.innerHTML,/Стадион «Динамо»/);
 assert.doesNotMatch(app.innerHTML,/<h3 class="game-title">360° Падел/);
 vm.runInContext("state.genderFilter='female';render()",context);assert.ok(app.innerHTML.includes('0 найдено'));
 vm.runInContext("state.genderFilter='male';render()",context);assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.games[0].creatorRole='player';state.games[0].creatorNtrp=3.0;state.myLevelOnly=true;render()",context);
 assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.games[0].creatorNtrp=5.0;render()",context);
 assert.ok(app.innerHTML.includes('0 найдено'));
});
