import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

test('offline HTML renders home, games, and create form without a server',async()=>{
 const dir=path.dirname(fileURLToPath(import.meta.url));
 const html=fs.readFileSync(path.join(dir,'../OPEN_DEMO.html'),'utf8');
 const source=html.split('<script>')[1]?.split('</script>')[0];assert.ok(source);
 const handlers={};const app={innerHTML:'',addEventListener(type,fn){(handlers[type]??=[]).push(fn)}};const storage=new Map();
 const context={window:{},document:{querySelector:q=>q==='#app'?app:null},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},crypto,Intl,Date,URLSearchParams,location:{search:'',origin:'file://'},navigator:{},setTimeout,console};
 vm.createContext(context);vm.runInContext(source,context);await new Promise(resolve=>setTimeout(resolve,20));
 assert.ok(app.innerHTML.includes('Добро пожаловать в Tennis GO'));
 assert.ok(app.innerHTML.includes('Я игрок')&&app.innerHTML.includes('Я тренер'));
 assert.ok(app.innerHTML.includes('data-back'));
 vm.runInContext("state.registrationRole='coach';state.registrationStep=2;render()",context);
 assert.ok(app.innerHTML.includes('registration-form')&&app.innerHTML.includes('Мужские')&&app.innerHTML.includes('Женские'));
 assert.ok(app.innerHTML.includes('Расскажите о вашем тренерском опыте'));
 assert.ok(app.innerHTML.includes('name="coachSports" value="tennis"')&&app.innerHTML.includes('name="coachSports" value="padel"'));
 assert.ok(app.innerHTML.includes('name="city"')&&app.innerHTML.includes('Анапа')&&app.innerHTML.includes('name="phone"')&&app.innerHTML.includes('name="telegramContact"'));
 assert.ok(app.innerHTML.includes('id="profile-ntrp-card" hidden'));
 vm.runInContext("state.registrationRole='player';state.registrationStep=2;render()",context);
 assert.ok(app.innerHTML.includes('value="unknown"')&&app.innerHTML.includes('Я не знаю свой уровень'));
 assert.equal(vm.runInContext("identityPayload(new Map([['name','Ира'],['role','player'],['gender','female'],['playingYears','0'],['ntrpLevel','unknown'],['city','Краснодар']])).ntrpLevel",context),1);
 assert.ok(app.innerHTML.includes('Астрахань')&&app.innerHTML.includes('Волгоград')&&app.innerHTML.includes('Севастополь'));
 vm.runInContext("state.registrationStep=1;render()",context);assert.ok(app.innerHTML.includes('Представитель клуба/корта'));
 vm.runInContext("state.registrationRole='club';state.registrationStep=2;render()",context);
 assert.ok(app.innerHTML.includes('name="clubName"')&&app.innerHTML.includes('name="clubAddress"')&&app.innerHTML.includes('name="clubPhone"'));
 assert.ok(app.innerHTML.includes('name="clubSurface"')&&app.innerHTML.includes('name="opensAt"')&&app.innerHTML.includes('name="closesAt"')&&app.innerHTML.includes('name="hourlyPrice"')&&app.innerHTML.includes('id="club-photo-input"'));
 vm.runInContext("state.registrationStep=3;render()",context);assert.ok(app.innerHTML.includes('Тренерский стаж, лет'));
 await vm.runInContext("api('/profile','POST',{name:'Роман',role:'player',gender:'male',playingYears:2,ntrpLevel:3.5,about:'',coachYears:null,photoData:null,avatarId:'male-cap'}).then(()=>refresh()).then(render)",context);
 assert.ok(app.innerHTML.includes('Подойдут вам')&&app.innerHTML.includes('Стадион «Динамо»'));
 assert.ok(app.innerHTML.includes('События Tennis GO')&&app.innerHTML.includes('ИГРОВОЙ МАРАФОН')&&app.innerHTML.includes('0 / 20'));
 assert.ok(app.innerHTML.includes('Приз: Туба теннисных мячей'));
 const quick=app.innerHTML.match(/<div class="quick">([\s\S]*?)<\/div>/)?.[1];
 assert.ok(quick);assert.equal((quick.match(/<button /g)||[]).length,4);
 for(const label of ['Новости','Сообщество','Клубы и корты','Тренера'])assert.ok(quick.includes(label));
 assert.ok(quick.includes('quick-icon')&&quick.includes('<svg'));
 assert.ok(app.innerHTML.includes('Telegram @RVL233')&&!app.innerHTML.includes('Прогноз:'));
 assert.ok(!quick.includes('Создать игру'));
 vm.runInContext("state.form='news';render()",context);
 assert.ok(app.innerHTML.includes('Новости')&&app.innerHTML.includes('Игровой марафон')&&app.innerHTML.includes('туба теннисных мячей'));
 vm.runInContext("state.me.isAdmin=true;state.news=[{id:'1',title:'Новый турнир',body:'Игры на выходных',publishedAt:new Date().toISOString()}];render()",context);
 assert.ok(app.innerHTML.includes('id="news-form"')&&app.innerHTML.includes('Опубликовать и уведомить всех')&&app.innerHTML.includes('Новый турнир'));
 vm.runInContext('state.me.isAdmin=false;state.news=[]',context);
 vm.runInContext("state.form='coaches';state.peopleMode='coach';render()",context);
 assert.ok(app.innerHTML.includes('Тренера')&&app.innerHTML.includes('Поиск по имени'));
 await vm.runInContext('loadPeople(true)',context);
 assert.ok(app.innerHTML.includes('Анастасия')&&!app.innerHTML.includes('Алексей'));
 vm.runInContext("state.form='courts';render()",context);
 assert.ok(app.innerHTML.includes('Клубы и корты')&&app.innerHTML.includes('court-city-filter')&&app.innerHTML.includes('Стадион «Динамо»'));
 vm.runInContext("state.form='event-marathon';render()",context);
 assert.ok(app.innerHTML.includes('Как участвовать')&&app.innerHTML.includes('На рейтинг'));
 vm.runInContext("state.form='';render()",context);
 assert.ok(app.innerHTML.includes('Активность и рейтинг')&&app.innerHTML.includes('compact-training')&&app.innerHTML.includes('стаж 7 лет'));
 assert.ok(app.innerHTML.includes('Пример')&&app.innerHTML.includes('<strong>30</strong><span>игр</span>')&&app.innerHTML.includes('<strong>20</strong><span>тренировок</span>'));
 vm.runInContext("state.tab='profile';render()",context);
 assert.ok(app.innerHTML.includes('Мой профиль')&&app.innerHTML.includes('progress-chart')&&app.innerHTML.includes('Пример'));
 vm.runInContext("state.tab='home';render()",context);
 assert.ok(app.innerHTML.includes('>Играть</button>')&&app.innerHTML.includes('>Профиль</button>'));
 assert.equal(vm.runInContext('recommendedEvents().length',context),2);
 vm.runInContext("state.games[0].opponentGender='female'",context);assert.equal(vm.runInContext('recommendedEvents().length',context),1);
 vm.runInContext("state.games[0].opponentGender='any';state.me.city='Анапа'",context);assert.equal(vm.runInContext('recommendedEvents().length',context),0);
 vm.runInContext("state.me.city='Краснодар';state.me.ntrpLevel=5.5",context);assert.equal(vm.runInContext('recommendedEvents().length',context),0);
 vm.runInContext("state.me.ntrpLevel=3.5;state.ratingHistory=[{sport:'tennis',previous:1500,current:1524,createdAt:new Date().toISOString()}];state.me.ratings={tennis:{rating:1524,matches:1,wins:1,losses:0}};state.progress={months:[{label:'май',games:0,trainings:0,rating:1500},{label:'июн',games:0,trainings:0,rating:1500},{label:'июл',games:0,trainings:0,rating:1500},{label:'авг',games:0,trainings:0,rating:1500},{label:'сен',games:1,trainings:0,rating:1524}],totalGames:1,totalTrainings:0,ratingDelta:24};render()",context);
 assert.ok(app.innerHTML.includes('+24')&&app.innerHTML.includes('progress-chart')&&app.innerHTML.includes('<strong>1</strong><span>игр</span>'));
 assert.ok(!app.innerHTML.includes('progress-demo-tag'));
 assert.ok(!app.innerHTML.includes('Теннис: ваш город, NTRP и свободные места'));
 vm.runInContext("state.games[0].joined=true;render()",context);
 assert.ok(app.innerHTML.includes('ВАШЕ БЛИЖАЙШЕЕ СОБЫТИЕ')&&app.innerHTML.includes('<img class="home-plan-art" src="data:image/png;base64,'));
 vm.runInContext("state.games[0].joined=false;state.trainings[0].joined=true;state.trainings[0].completed=true;state.progress.totalTrainings=1;state.progress.months[4].trainings=1;render()",context);
 assert.ok(app.innerHTML.includes('ВАШЕ БЛИЖАЙШЕЕ СОБЫТИЕ')&&!app.innerHTML.includes('home-plan-art'));
 assert.ok(app.innerHTML.includes('<strong>1</strong><span>тренировок</span>'));
 vm.runInContext("state.trainings[0].joined=false;state.trainings[0].completed=false;render()",context);
 vm.runInContext("state.weather=[{time:state.games[0].startsAt,temperature:24.4,code:0}];render()",context);
 assert.ok(app.innerHTML.includes('☀️ 24°'));
 vm.runInContext("state.weather=[{time:state.games[0].startsAt,temperature:19.4,code:3}];render()",context);
 assert.ok(app.innerHTML.includes('☁️ 19°'));
 vm.runInContext("state.weather=[{time:state.games[0].startsAt,temperature:17.4,code:61}];render()",context);
 assert.ok(app.innerHTML.includes('🌧️ 17°'));
 assert.ok(app.innerHTML.includes('home-section')&&app.innerHTML.includes('home-rating'));
 assert.ok(app.innerHTML.includes('СПАРРИНГ')&&app.innerHTML.includes('Тренер - Анастасия')&&app.innerHTML.includes('Сплит · 2 человека · стаж 7 лет'));
 assert.ok(!app.innerHTML.includes('360° Падел'));
 assert.ok(!vm.runInContext('compactGameCard(state.games[0])',context).includes('ПАРНАЯ'));
 assert.ok(vm.runInContext('gameCard(state.games[1])',context).includes('ПАРНАЯ'));
 assert.ok(vm.runInContext('gameDetail(state.games[1])',context).includes('ПАРНАЯ'));
 assert.ok(app.innerHTML.includes('2 места свободно'));
 assert.ok(!app.innerHTML.includes('class="filters"'));
 vm.runInContext("state.filter='tennis';render()",context);
 assert.ok(!app.innerHTML.includes('360° Падел'));
 vm.runInContext("state.filter='all';render()",context);
 vm.runInContext("state.games[0].members.push({id:'demo-filled',name:'Игрок'});state.trainings[0].members.push({id:'a',name:'A'},{id:'b',name:'B'});render()",context);
 assert.ok(!app.innerHTML.includes('compact-training')&&!app.innerHTML.includes('Стадион «Динамо»'));
 vm.runInContext("state.games[0].members.pop();state.trainings[0].members=[];render()",context);
 assert.ok(app.innerHTML.includes('Играть</button>'));
 vm.runInContext("state.tab='play';state.playView='games';render()",context);
 assert.ok(app.innerHTML.includes('class="play-title">Играть')&&app.innerHTML.includes('data-play-view="games"')&&app.innerHTML.includes('Найти игру'));
 assert.ok(app.innerHTML.includes('data-locate')&&app.innerHTML.includes('© OpenStreetMap'));
 vm.runInContext("state.catalog.courts[0].latitude=45;state.catalog.courts[0].longitude=39;state.location={latitude:45,longitude:39};render()",context);
 assert.ok(app.innerHTML.includes('Рядом · 0.0 км'));
 assert.ok(vm.runInContext("(state.location.latitude=45.06,distanceBadge('dinamo'))",context).includes('Близко'));
 assert.ok(vm.runInContext("(state.location.latitude=45.11,distanceBadge('dinamo'))",context).includes('Далеко'));
 vm.runInContext('state.location=null;render()',context);
 assert.ok(app.innerHTML.includes('data-play-view="tournaments"')&&app.innerHTML.includes('data-play-view="camps"'));
 vm.runInContext("state.playView='tournaments';render()",context);assert.ok(app.innerHTML.includes('Раздел находится в разработке'));
 vm.runInContext("state.playView='camps';render()",context);assert.ok(app.innerHTML.includes('Раздел находится в разработке'));
 vm.runInContext("state.playView='games';render()",context);
 await handlers.click[0]({target:{closest:()=>({dataset:{playView:'training'}})}});
 assert.ok(app.innerHTML.includes('data-play-view="training"')&&app.innerHTML.includes('Занятия, опубликованные тренерами'));
 vm.runInContext("state.tab='home';state.playView='games';render()",context);
 assert.ok(app.innerHTML.includes('Сообщество')&&app.innerHTML.includes('data-tab="community"')&&app.innerHTML.includes('id="chat-badge"'));
 const nav=app.innerHTML.match(/<nav class="nav"[^>]*>([\s\S]*?)<\/nav>/)?.[1];
 assert.ok(nav);assert.deepEqual([...nav.matchAll(/data-tab="([^"]+)"/g)].map(m=>m[1]),['home','play','chat','profile']);
 assert.ok(nav.includes('>Чат')&&nav.includes('<circle cx="12" cy="12" r="9"'));
 assert.ok(!app.innerHTML.includes('data-back'));
 assert.ok(app.innerHTML.includes('class="brand-logo"><img src="data:image/png;base64,'));
 vm.runInContext("state.tab='games'; render()",context);assert.match(app.innerHTML,/Найти игру/);
 vm.runInContext("state.tab='training';state.me.role='player';render()",context);
 assert.ok(app.innerHTML.includes('<h1 class="page-title">Тренировки</h1>')&&!app.innerHTML.includes('Создать тренировку'));
 vm.runInContext("state.tab='community';state.communityTab='people';state.people=[{id:'demo-host',name:'Алексей',role:'player',city:'Краснодар',avatarId:'male-cap'}];render()",context);
 assert.ok(app.innerHTML.includes('data-direct="demo-host"')&&app.innerHTML.includes('data-user="demo-host"'));
 assert.ok(app.innerHTML.includes('data-community="rating"')&&app.innerHTML.includes('data-community="events"')&&app.innerHTML.includes('data-community="resources"'));
 assert.ok(!app.innerHTML.includes('data-community="chats"'));
 vm.runInContext("state.communityTab='resources';render()",context);assert.ok(app.innerHTML.includes('Федерация тенниса России')&&app.innerHTML.includes('target="_blank"'));
 vm.runInContext("state.communityTab='events';render()",context);assert.ok(app.innerHTML.includes('Мероприятия')&&app.innerHTML.includes('Игровой марафон')&&app.innerHTML.includes('туба теннисных мячей'));
 vm.runInContext("state.communityTab='rating';render()",context);assert.ok(app.innerHTML.includes('Пока нет рейтинговых матчей'));
 vm.runInContext("state.tab='chat';state.unread=2;state.inbox=[{key:'direct:demo-host',peerName:'Алексей',title:'Личный чат',lastMessage:'Привет',unread:2}];render()",context);
 assert.ok(app.innerHTML.includes('data-inbox-thread="direct:demo-host"')&&app.innerHTML.includes('class="unread-pill">2</b>'));
 vm.runInContext("state.tab='games';render()",context);
 assert.ok(app.innerHTML.includes('Игроки и корты рядом с вами.')&&!app.innerHTML.includes('Игроки и корты Краснодара'));
 assert.ok(app.innerHTML.includes('data-direct="demo-host"')&&app.innerHTML.includes('data-user="demo-host"')&&app.innerHTML.includes('data-game="'));
 context.gameId=vm.runInContext('state.games[0].id',context);
 await handlers.click[0]({target:{closest:()=>({dataset:{direct:'demo-host',name:'Алексей'},hasAttribute:()=>false})}});
 assert.equal(vm.runInContext('state.chat.kind',context),'direct');
 vm.runInContext('back()',context);
 await handlers.click[0]({target:{closest:()=>({dataset:{game:context.gameId},hasAttribute:()=>false})}});
 assert.equal(vm.runInContext('state.detail.id',context),context.gameId);
 assert.ok(app.innerHTML.includes('detail-organizer')&&app.innerHTML.includes('data-user="demo-host"')&&app.innerHTML.includes('Написать организатору'));
 vm.runInContext('back()',context);
 vm.runInContext("state.form='create'; render()",context);assert.ok(app.innerHTML.includes('id="create-form"'));assert.ok(app.innerHTML.includes('4 игрока · парная'));assert.ok(app.innerHTML.includes('Академия «Вопреки» — ул. Невкипелого, 24/4'));assert.ok(app.innerHTML.includes('Что означают уровни NTRP 1.0–7.0?'));assert.ok(app.innerHTML.includes('Ракетка для падела'));assert.ok(app.innerHTML.includes('Кто может присоединиться'));
 assert.ok(app.innerHTML.includes('На рейтинг')&&app.innerHTML.includes('name="requiresApproval"'));
 vm.runInContext("state.form='edit-profile'; render()",context);assert.ok(app.innerHTML.includes('id="profile-form"'));assert.ok(app.innerHTML.includes('Своя фотография'));assert.ok(app.innerHTML.includes('Уровень тенниса · NTRP'));
 assert.ok(app.innerHTML.includes('name="city"')&&app.innerHTML.includes('name="phone"'));
 vm.runInContext("state.form='';state.tab='profile';state.me.role='coach';render()",context);
 assert.ok(app.innerHTML.includes('Создать тренировку'));
 assert.ok(!app.innerHTML.includes('Уровень тенниса · NTRP'));
 vm.runInContext("state.me.role='player';state.me.ratings={tennis:{rating:1584,matches:4,wins:3,losses:1},padel:{rating:1500,matches:0,wins:0,losses:0}};render()",context);
 assert.ok(app.innerHTML.includes('Tennis GO')&&app.innerHTML.includes('1584')&&app.innerHTML.includes('Предварительный'));
 vm.runInContext("state.me.role='coach';state.tab='home';render()",context);
 assert.ok(app.innerHTML.includes('Тренера')&&!app.innerHTML.includes('class="primary training-action"'));
 vm.runInContext("state.form='create-training';render()",context);
 assert.ok(app.innerHTML.includes('id="training-form"')&&app.innerHTML.includes('Сплит · 2 человека')&&app.innerHTML.includes('NTRP от')&&app.innerHTML.includes('NTRP до'));
 assert.ok(app.innerHTML.includes('<option value="padel">Падел</option>')&&app.innerHTML.includes('Стадион «Динамо»'));
 vm.runInContext("state.me.coachSports=['padel'];render()",context);
 assert.ok(app.innerHTML.includes('<option value="padel">Падел</option>')&&!app.innerHTML.includes('<option value="tennis">🎾 Теннис</option>'));
 assert.ok(app.innerHTML.includes('360° Падел — ул. Тополиная, 33А'));
 vm.runInContext("state.me.coachSports=['tennis','padel'];render()",context);
 assert.ok(!app.innerHTML.includes('360° Падел — ул. Тополиная, 33А'));
 const courtSelect={innerHTML:''},trainingForm={elements:{courtId:courtSelect}};
 context.trainingSport={name:'sport',value:'padel',form:trainingForm,closest:()=>trainingForm};
 for(const handler of handlers.change)await handler({target:context.trainingSport});
 assert.match(courtSelect.innerHTML,/360° Падел — ул. Тополиная, 33А/);
 assert.ok(app.innerHTML.includes('data-back'));
 vm.runInContext("state.me.role='player';state.form='';render()",context);
 vm.runInContext("state.tab='training';render()",context);
 assert.ok(app.innerHTML.includes('>Тренировки</h1>')&&app.innerHTML.includes('training-gender-filter')&&app.innerHTML.includes('training-format-filter'));
 assert.ok(app.innerHTML.includes('data-direct="demo-coach"'));
 assert.ok(app.innerHTML.includes('data-user="demo-coach"')&&app.innerHTML.includes('Тренер - Анастасия'));
 assert.ok(app.innerHTML.includes('training-sport-filter')&&app.innerHTML.includes('Теннис и падел'));
 vm.runInContext("state.trainingSport='padel';render()",context);assert.ok(app.innerHTML.includes('0 найдено'));
 vm.runInContext("state.trainingSport='tennis';render()",context);assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.trainingSport='all';render()",context);
 assert.ok(app.innerHTML.includes('data-training-court="dinamo"')&&app.innerHTML.includes('data-training-court="padel360"'));
 assert.ok(!app.innerHTML.includes('booking-form')&&!app.innerHTML.includes('Индивидуальная заявка'));
 vm.runInContext("state.trainingGender='male';render()",context);assert.ok(app.innerHTML.includes('0 найдено'));
 vm.runInContext("state.trainingGender='all';state.trainingCourts=['padel360'];render()",context);assert.ok(app.innerHTML.includes('0 найдено'));
 vm.runInContext("state.trainingCourts=['padel360','dinamo'];render()",context);assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.trainingFormat='individual';render()",context);assert.ok(app.innerHTML.includes('0 найдено'));
 vm.runInContext("state.trainingFormat='all';state.trainingGender='all';state.trainingCourts=[];state.trainings[0].members.push({id:'demo-host',name:'Алексей',avatarId:'male-cap'});render()",context);
 assert.ok(app.innerHTML.includes('participant-strip'));
 vm.runInContext('openTraining(state.trainings[0].id)',context);
 assert.ok(app.innerHTML.includes('Записались · 1/2')&&app.innerHTML.includes('data-user="demo-host"'));
 vm.runInContext('state.trainings[0].coachId=state.me.id;render()',context);
 assert.ok(app.innerHTML.includes('data-edit="training:')&&app.innerHTML.includes('Отменить объявление'));
 vm.runInContext("state.editTarget={kind:'training',id:state.trainings[0].id};state.trainingDetail=null;state.form='edit-training';render()",context);
 assert.ok(app.innerHTML.includes('id="edit-training-form"')&&app.innerHTML.includes('Сплит'));
 vm.runInContext("state.form='';state.editTarget=null;state.trainings[0].coachId='demo-coach';state.trainingDetail=state.trainings[0];render()",context);
 await vm.runInContext("openUser('demo-host')",context);
 assert.ok(app.innerHTML.includes('Профиль участника')&&app.innerHTML.includes('Алексей')&&app.innerHTML.includes('Написать лично'));
 vm.runInContext('back()',context);assert.ok(app.innerHTML.includes('Записались · 1/2'));
 vm.runInContext('back()',context);assert.ok(app.innerHTML.includes('>Тренировки</h1>'));
 vm.runInContext('openGame(state.games[0].id)',context);assert.ok(app.innerHTML.includes('data-user="demo-host"'));
 await vm.runInContext("openChat('game',state.games[0].id)",context);
 assert.ok(app.innerHTML.includes('id="chat-form"')&&app.innerHTML.includes('Обновить сообщения'));
 await vm.runInContext("api('/chats/game/'+state.games[0].id+'/demo-host','POST',{message:'Здравствуйте!'}).then(()=>refreshChat())",context);
 assert.ok(app.innerHTML.includes('Здравствуйте!'));
 vm.runInContext('back()',context);assert.ok(app.innerHTML.includes('Участники'));
 vm.runInContext('state.games[0].creatorId=state.me.id;render()',context);
 assert.ok(app.innerHTML.includes('Редактировать')&&app.innerHTML.includes('Отменить объявление'));
 vm.runInContext("state.editTarget={kind:'game',id:state.games[0].id};state.detail=null;state.form='edit-game';render()",context);
 assert.ok(app.innerHTML.includes('id="edit-game-form"')&&app.innerHTML.includes('Сохранить изменения'));
 vm.runInContext("state.form='';state.editTarget=null;state.games[0].creatorId='demo-host';state.detail=state.games[0];render()",context);
 vm.runInContext('back()',context);
 vm.runInContext("state.tab='home';state.history=[];pushView();state.tab='training';render();back()",context);
 assert.ok(app.innerHTML.includes('Подойдут вам'));
 const boxes={'#level-guide-items':{innerHTML:''},'#court-address':{textContent:''},'#level-summary':{innerHTML:''}};
 const form={elements:{sport:{value:'padel'},seats:{value:'2'},courtId:{value:'padel360',innerHTML:''},levelMin:{value:'2.5',innerHTML:''},levelMax:{value:'3.5',innerHTML:''}},querySelector:q=>boxes[q]};
 context.fakeForm=form;vm.runInContext('updateCreateChoices(fakeForm)',context);
 assert.equal(form.elements.seats.value,'4');
 assert.match(form.elements.courtId.innerHTML,/360° Падел — ул. Тополиная, 33А/);
 assert.doesNotMatch(form.elements.courtId.innerHTML,/Стадион «Динамо»/);
 assert.match(boxes['#level-guide-items'].innerHTML,/Использую стены/);
 form.elements.rating={checked:true};vm.runInContext('syncGameFormat(fakeForm)',context);
 assert.equal(form.elements.seats.value,'4');
 assert.ok(vm.runInContext("createPage()",context).includes('name="rating"'));
 assert.ok(!vm.runInContext("createPage()",context).includes('name="kind"'));
 vm.runInContext("state.form='';state.tab='games';state.filter='all';state.when='all';state.courts=['dinamo','padel360'];state.availableOnly=true;render()",context);
 assert.ok(app.innerHTML.includes('Пол игроков')&&app.innerHTML.includes('data-rating-only'));
 assert.ok(app.innerHTML.includes('<option value="Ростов-на-Дону"')&&app.innerHTML.includes('<option value="Элиста"'));
 assert.equal(vm.runInContext('visibleGames({advanced:true}).length',context),2);
 assert.ok(app.innerHTML.includes('Корты · выбрано 2'));
 const summary={textContent:''};
 for(const handler of handlers.change)await handler({target:{dataset:{gameCourt:'padel360'},checked:false,closest:()=>({querySelector:()=>summary})}});
 assert.equal(vm.runInContext('state.courts.length',context),1);
 assert.equal(summary.textContent,'Корты · выбрано 1');
 vm.runInContext("state.courts=['dinamo'];render()",context);
 assert.equal(vm.runInContext('visibleGames({advanced:true}).length',context),1);
 assert.ok(app.innerHTML.includes('1 найдено'));
 assert.match(app.innerHTML,/Стадион «Динамо»/);
 assert.doesNotMatch(app.innerHTML,/<h3 class="game-title">360° Падел/);
 vm.runInContext("state.genderFilter='female';render()",context);assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.genderFilter='male';render()",context);assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.genderFilter='all';state.ratingOnly=true;render()",context);assert.ok(app.innerHTML.includes('0 найдено'));
 vm.runInContext("state.games[0].kind='rating';render()",context);assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.ratingOnly=false;state.games[0].kind='friendly';render()",context);
 const upcoming=vm.runInContext('state.games[0].startsAt',context);
 vm.runInContext("state.games[0].startsAt=new Date(Date.now()-60000).toISOString();render()",context);
 assert.equal(vm.runInContext('visibleGames({advanced:true}).length',context),0);
 context.upcoming=upcoming;vm.runInContext('state.games[0].startsAt=upcoming;render()',context);
 vm.runInContext("state.games[0].creatorRole='player';state.games[0].creatorNtrp=3.0;state.myLevelOnly=true;render()",context);
 assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.games[0].creatorNtrp=5.0;render()",context);
 assert.ok(app.innerHTML.includes('0 найдено'));
 context.FileReader=class{readAsDataURL(){this.result='data:image/png;base64,AAAA';queueMicrotask(()=>this.onload());}};
 context.Image=class{set src(value){this.naturalWidth=800;this.naturalHeight=600;queueMicrotask(()=>this.onload());}};
 context.document.createElement=()=>({getContext:()=>({drawImage(){}}),toDataURL:()=>"data:image/jpeg;base64,/9j/2Q=="});
 const jpeg=await vm.runInContext("imageData({type:'image/png',size:100})",context);
 assert.equal(jpeg,'data:image/jpeg;base64,/9j/2Q==');
 vm.runInContext("state.me.role='club';state.me.club={name:'Теннис Парк',city:'Ростов-на-Дону',address:'ул. Тестовая, 12',phone:'+7 900 123-45-67',sports:['tennis'],status:'approved'};state.form='';state.clubDate='2026-09-28';state.clubCalendar=[{startsAt:'2026-09-28T15:00:00Z',duration:90,sport:'tennis',guestName:'Вика'}];render()",context);
 assert.ok(app.innerHTML.includes('Календарь клуба')&&app.innerHTML.includes('Забронировал: Вика'));
 assert.ok(!app.innerHTML.includes('class="nav"'));
});
