import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

test('offline HTML renders home, games, and create form without a server',async()=>{
 const dir=path.dirname(fileURLToPath(import.meta.url));
 const html=fs.readFileSync(path.join(dir,'../OPEN_DEMO.html'),'utf8');
 const source=html.split('<script>')[1]?.split('</script>')[0];assert.ok(source);
 const handlers={};const app={innerHTML:'',addEventListener(type,fn){(handlers[type]??=[]).push(fn)}};const storage=new Map();
 const context={window:{},document:{querySelector:q=>q==='#app'?app:null},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},crypto,Intl,Date,URLSearchParams,location:{search:'',origin:'file://'},navigator:{},setTimeout,console};
 vm.createContext(context);vm.runInContext(source,context);await new Promise(resolve=>setTimeout(resolve,20));
 assert.ok(app.innerHTML.includes('Добро пожаловать в Tennis GO'));
 assert.ok(app.innerHTML.includes('Я игрок')&&app.innerHTML.includes('Я тренер'));
 assert.ok(app.innerHTML.includes('data-back'));
 vm.runInContext("state.registrationRole='coach';state.registrationStep=2;render()",context);
 assert.ok(app.innerHTML.includes('registration-form')&&app.innerHTML.includes('Мужские')&&app.innerHTML.includes('Женские'));
 assert.ok(app.innerHTML.includes('name="firstName"')&&app.innerHTML.includes('name="lastName"')&&app.innerHTML.includes('Телефон <span class="required-star">*</span>')&&app.innerHTML.includes('Telegram <span class="required-star">*</span>'));
 assert.ok(app.innerHTML.includes('Расскажите о вашем тренерском опыте'));
 assert.ok(app.innerHTML.includes('name="coachSports" value="tennis"')&&app.innerHTML.includes('name="coachSports" value="padel"'));
 assert.ok(app.innerHTML.includes('name="city"')&&app.innerHTML.includes('Анапа')&&app.innerHTML.includes('name="phone"')&&app.innerHTML.includes('name="telegramContact"'));
 assert.ok(app.innerHTML.includes('id="profile-ntrp-card" hidden'));
 vm.runInContext("state.registrationRole='player';state.registrationStep=2;render()",context);
 assert.ok(app.innerHTML.includes('Телефон игрока используется только при бронировании корта'));
 assert.ok(app.innerHTML.includes('value="unknown"')&&app.innerHTML.includes('Я не знаю свой уровень')&&app.innerHTML.includes('required-guide')&&app.innerHTML.includes('required-star'));
 assert.equal(vm.runInContext("identityPayload(new Map([['name','Ира'],['role','player'],['gender','female'],['playingYears','0'],['ntrpLevel','unknown'],['city','Краснодар']])).ntrpLevel",context),1);
 assert.ok(app.innerHTML.includes('Астрахань')&&app.innerHTML.includes('Волгоград')&&app.innerHTML.includes('Севастополь'));
 vm.runInContext("state.registrationStep=1;render()",context);assert.ok(app.innerHTML.includes('Представитель клуба/корта'));
 vm.runInContext("state.registrationRole='club';state.registrationStep=2;render()",context);
 assert.ok(app.innerHTML.includes('name="clubName"')&&app.innerHTML.includes('name="clubAddress"')&&app.innerHTML.includes('name="clubPhone"'));
 assert.ok(app.innerHTML.includes('name="clubSurface"')&&app.innerHTML.includes('name="opensAt"')&&app.innerHTML.includes('name="closesAt"')&&app.innerHTML.includes('name="hourlyPrice"')&&app.innerHTML.includes('id="club-photo-input"'));
 vm.runInContext("state.registrationStep=3;render()",context);assert.ok(app.innerHTML.includes('Тренерский стаж, лет'));
 await vm.runInContext("api('/profile','POST',{name:'Роман Игрок',phone:'+7 999 123-45-67',role:'player',gender:'male',playingYears:2,ntrpLevel:3.5,about:'',coachYears:null,photoData:null,avatarId:'male-cap'}).then(()=>refresh()).then(render)",context);
 assert.ok(app.innerHTML.includes('data-city-menu')&&app.innerHTML.includes('class="top-avatar"')&&app.innerHTML.includes('data-tab="profile"'));
 assert.ok(!app.innerHTML.includes('Сейчас в сети')&&!app.innerHTML.includes('online-panel'));
 assert.ok(app.innerHTML.includes('Подойдут вам')&&app.innerHTML.includes('Стадион «Динамо»'));
 assert.ok(app.innerHTML.includes('События Tennis GO')&&app.innerHTML.includes('ИГРОВОЙ МАРАФОН')&&app.innerHTML.includes('0 / 20')&&app.innerHTML.includes('data-event-step="1"'));
 assert.ok(app.innerHTML.includes('Приз: Туба теннисных мячей'));
 vm.runInContext("state.news=[{id:'one',title:'Новость один',body:'Текст один',publishedAt:new Date().toISOString()},{id:'two',title:'Новость два',body:'Текст два',publishedAt:new Date().toISOString()}];moveEvent(1)",context);
 assert.ok(app.innerHTML.includes('Новость один')&&app.innerHTML.includes('events-dots'));
 vm.runInContext('moveEvent(1)',context);assert.ok(app.innerHTML.includes('Новость два'));
 vm.runInContext('moveEvent(1)',context);assert.ok(app.innerHTML.includes('ИГРОВОЙ МАРАФОН'));
 vm.runInContext('state.news=[];state.eventIndex=0;render()',context);

 const quick=app.innerHTML.match(/<div class="quick">([\s\S]*?)<\/div>/)?.[1];
 assert.ok(quick);assert.equal((quick.match(/<button /g)||[]).length,4);
 for(const label of ['Новости','Сообщество','Клубы и корты','Тренера'])assert.ok(quick.includes(label));
 assert.ok(quick.includes('quick-icon')&&quick.includes('<svg'));
 assert.ok(app.innerHTML.includes('Telegram @RVL233')&&!app.innerHTML.includes('Прогноз:'));
 assert.ok(!quick.includes('Создать игру'));
 vm.runInContext("state.form='news';render()",context);
 assert.ok(app.innerHTML.includes('Новости')&&app.innerHTML.includes('Игровой марафон')&&app.innerHTML.includes('туба теннисных мячей'));
 vm.runInContext("state.me.isAdmin=true;state.news=[{id:'1',title:'Новый турнир',body:'Игры на выходных',publishedAt:new Date().toISOString()}];render()",context);
 assert.ok(app.innerHTML.includes('id="news-form"')&&app.innerHTML.includes('Опубликовать и уведомить всех')&&app.innerHTML.includes('Новый турнир'));
 vm.runInContext("state.form='admin';state.adminStats={total:12,onlineNow:3,newToday:2,new7:5,new30:10,activeToday:4,active7:8,active30:9,last7:{games:3,trainings:2,joins:4,messages:7,bookings:1,news:1},daily:Array.from({length:30},(_,i)=>({day:'2026-09-'+String(i+1).padStart(2,'0'),active:1,games:1,trainings:0,messages:0}))};render()",context);
 assert.ok(app.innerHTML.includes('Управление Tennis GO')&&app.innerHTML.includes('Активность за 14 дней')&&app.innerHTML.includes('Новых за 7 дней')&&app.innerHTML.includes('Сейчас онлайн')&&app.innerHTML.includes('<strong>3</strong>'));
 vm.runInContext("state.adminTab='messages';state.adminMessages=[{kind:'direct',id:'123',senderName:'Алексей',recipientName:'Роман',body:'Привет',createdAt:new Date().toISOString()}];render()",context);
 assert.ok(app.innerHTML.includes('data-admin-ask="message:direct:123"'));
 vm.runInContext("state.adminTab='users';state.adminUsers=[{id:'demo-host',name:'Алексей',role:'player',city:'Краснодар',blockedAt:null}];render()",context);
 assert.ok(app.innerHTML.includes('data-admin-block="demo-host"'));
 vm.runInContext("state.adminTab='preview';state.previewRole='coach';state.previewTab='play';render()",context);
 assert.ok(app.innerHTML.includes('data-preview-role="club"')&&app.innerHTML.includes('Создать тренировку'));
 vm.runInContext("state.previewRole='club';state.previewTab='home';render()",context);
 assert.ok(app.innerHTML.includes('Календарь клуба')&&app.innerHTML.includes('Пример игрока'));
 vm.runInContext("state.previewRole='player';state.previewTab='home';render()",context);
 assert.ok(app.innerHTML.includes('data-preview-tab="play"')&&app.innerHTML.includes('Подойдут вам'));
 assert.equal(vm.runInContext('state.me.isAdmin',context),true);
 vm.runInContext('state.me.isAdmin=false;state.news=[]',context);
 vm.runInContext("state.form='coaches';state.peopleMode='coach';render()",context);
 assert.ok(app.innerHTML.includes('Тренеры')&&app.innerHTML.includes('Поиск по имени'));
 await vm.runInContext('loadPeople(true)',context);
 assert.ok(app.innerHTML.includes('Анастасия')&&!app.innerHTML.includes('Алексей'));
 assert.ok(app.innerHTML.includes('Тренерский стаж: 7 лет')&&app.innerHTML.includes('Призёр региональных турниров'));
 assert.ok(app.innerHTML.includes('coach-directory-avatar avatar" data-user="demo-coach"'));
 vm.runInContext("state.form='courts';render()",context);
 assert.ok(app.innerHTML.includes('Клубы и корты')&&app.innerHTML.includes('court-city-filter')&&app.innerHTML.includes('Динамо-Кубань'));
 assert.ok(app.innerHTML.includes('data-call-phone="+78619913139"')&&app.innerHTML.includes('data-call-phone="+79881301486"'));
 assert.ok(app.innerHTML.includes('data-call-club="')&&app.innerHTML.includes('Позвонить в клуб'));
 const callPage=fs.readFileSync(path.join(dir,'../public/call.html'),'utf8');
 assert.ok(callPage.includes("document.querySelector('#dial').href='tel:'+number")&&callPage.includes('Скопировать номер'));
 context.URL=URL;context.window.location={href:''};context.location.origin='https://tennis.example';
 vm.runInContext("openCall('+7 (861) 991-31-39','Динамо')",context);
 assert.ok(app.innerHTML.includes('href="tel:+78619913139"')&&app.innerHTML.includes('data-call-copy')&&app.innerHTML.includes('Динамо'));
 vm.runInContext('state.callSheet=null;render()',context);
 vm.runInContext("state.form='';state.tab='play';state.playView='training';state.trainingCalendarDate=dayKey(state.trainings[0].startsAt);state.trainingCalendarView='week';render()",context);
 assert.ok(app.innerHTML.includes('training-calendar-grid')&&app.innerHTML.includes('data-cal-view="day"')&&app.innerHTML.includes('data-cal-view="month"'));
 const calendar=app.innerHTML.match(/<div class="training-calendar-grid"[\s\S]*?<div class="training-calendar-foot">/)?.[0];
 assert.ok(calendar);
 assert.ok((calendar.match(/class="training-calendar-row"/g)||[]).length>=2);
 assert.ok(calendar.includes('style="display:flex;flex-wrap:nowrap;width:max-content"'));
 assert.ok(calendar.includes('class="training-calendar-date')&&calendar.includes('class="training-calendar-cell"'));
 assert.ok(!calendar.includes('grid-template-columns'));
 assert.equal(vm.runInContext("trainingCalendarColumns('month','2026-09-30',[]).length",context),30);
 assert.equal(vm.runInContext("trainingCalendarColumns('month','2026-09-30',[]).at(-1).key",context),'2026-10-29');
 assert.ok(app.innerHTML.includes('training-calendar-coach-avatar avatar" data-user="demo-coach"'));
 assert.ok(app.innerHTML.includes('format-split')&&app.innerHTML.includes('0/2 записано'));
 vm.runInContext("state.trainingCalendarView='day';render()",context);assert.ok(app.innerHTML.includes('training-calendar-date')&&app.innerHTML.includes(':00'));
 vm.runInContext("state.trainingCalendarView='month';render()",context);assert.ok(app.innerHTML.includes('data-calendar-focus='));
 vm.runInContext("state.form='event-marathon';render()",context);
 assert.ok(app.innerHTML.includes('Как участвовать')&&app.innerHTML.includes('На рейтинг'));
 vm.runInContext("state.form='';state.tab='home';render()",context);
 assert.ok(app.innerHTML.includes('Активность и рейтинг')&&app.innerHTML.includes('compact-training')&&app.innerHTML.includes('стаж 7 лет'));
 assert.ok(app.innerHTML.includes('Пример')&&app.innerHTML.includes('<strong>30</strong><span>игр</span>')&&app.innerHTML.includes('<strong>20</strong><span>тренировок</span>'));
 vm.runInContext("state.tab='profile';render()",context);
 assert.ok(app.innerHTML.includes('Мой профиль')&&!app.innerHTML.includes('progress-chart'));
 vm.runInContext("state.form='my-rating';render()",context);assert.ok(app.innerHTML.includes('Мой рейтинг')&&app.innerHTML.includes('progress-chart'));vm.runInContext("state.form='';render()",context);
 assert.ok(app.innerHTML.includes('class="profile-settings"')&&app.innerHTML.includes('profile-summary')&&app.innerHTML.includes('Мой рейтинг')&&app.innerHTML.includes('Мои активности и записи')&&app.innerHTML.includes('Личные данные и контакты')&&app.innerHTML.includes('>Достижения</h2>'));
 vm.runInContext("state.tab='home';render()",context);
 assert.ok(app.innerHTML.includes('>Играть</button>')&&app.innerHTML.includes('>Профиль</button>'));
 assert.equal(vm.runInContext('recommendedEvents().length',context),3);
 await vm.runInContext("api('/preferences/sports','PATCH',{sports:['padel']}).then(()=>refresh()).then(render)",context);
 assert.ok(app.innerHTML.includes('data-sport-pref="padel" checked')&&!app.innerHTML.includes('Турнир по теннису среди мужчин'));
 assert.equal(vm.runInContext("preferredSport()",context),'padel');
 assert.equal(vm.runInContext('recommendedEvents().length',context),1);
 vm.runInContext("state.form='news';render()",context);assert.ok(!app.innerHTML.includes('Турнир по теннису среди мужчин'));
 vm.runInContext("state.form='';state.tab='play';render()",context);assert.ok(!app.innerHTML.includes('data-filter="tennis"'));
 await vm.runInContext("api('/preferences/sports','PATCH',{sports:[]}).then(()=>refresh()).then(render)",context);
 assert.equal(vm.runInContext('recommendedEvents().length',context),3);
 vm.runInContext("state.form='news';render()",context);assert.ok(app.innerHTML.includes('Турнир по теннису среди мужчин')&&app.innerHTML.includes('news-poster'));
 vm.runInContext("state.form='';state.tab='home';render()",context);
 vm.runInContext("state.games[0].opponentGender='female'",context);assert.equal(vm.runInContext('recommendedEvents().length',context),2);
 vm.runInContext("state.games[0].opponentGender='any';state.me.city='Анапа'",context);assert.equal(vm.runInContext('recommendedEvents().length',context),0);
 vm.runInContext("state.me.city='Краснодар';state.me.ntrpLevel=5.5",context);assert.equal(vm.runInContext('recommendedEvents().length',context),0);
 vm.runInContext("state.me.ntrpLevel=3.5;state.ratingHistory=[{sport:'tennis',previous:1500,current:1524,createdAt:new Date().toISOString()}];state.me.ratings={tennis:{rating:1524,matches:1,wins:1,losses:0}};state.progress={months:[{label:'май',games:0,trainings:0,rating:1500},{label:'июн',games:0,trainings:0,rating:1500},{label:'июл',games:0,trainings:0,rating:1500},{label:'авг',games:0,trainings:0,rating:1500},{label:'сен',games:1,trainings:0,rating:1524}],totalGames:1,totalTrainings:0,ratingDelta:24};render()",context);
 assert.ok(app.innerHTML.includes('+24')&&app.innerHTML.includes('progress-chart')&&app.innerHTML.includes('<strong>1</strong><span>игр</span>'));
 assert.ok(!app.innerHTML.includes('progress-demo-tag'));
 assert.ok(!app.innerHTML.includes('Теннис: ваш город, NTRP и свободные места'));
 vm.runInContext("state.games[0].joined=true;render()",context);
 assert.ok(app.innerHTML.includes('ВАШЕ БЛИЖАЙШЕЕ СОБЫТИЕ')&&app.innerHTML.includes('<img class="home-plan-art')&&app.innerHTML.includes('src="data:image/webp;base64,'));
 vm.runInContext("state.games[0].joined=false;state.trainings[0].joined=true;state.trainings[0].completed=true;state.progress.totalTrainings=1;state.progress.months[4].trainings=1;render()",context);
 assert.ok(app.innerHTML.includes('ВАШЕ БЛИЖАЙШЕЕ СОБЫТИЕ')&&app.innerHTML.includes('home-plan-art training-art')); 
 assert.ok(app.innerHTML.includes('<strong>1</strong><span>тренировок</span>'));
 vm.runInContext("state.trainings[0].joined=false;state.trainings[0].completed=false;render()",context);
 vm.runInContext("state.games[1].joined=true;render()",context);
 assert.ok(app.innerHTML.includes('home-plan-art doubles-art')&&app.innerHTML.includes('src="data:image/webp;base64,'));
 vm.runInContext("state.games[1].joined=false;render()",context);
 vm.runInContext("state.weather=[{time:state.games[0].startsAt,temperature:24.4,code:0}];render()",context);
 assert.ok(app.innerHTML.includes('☀️ 24°'));
 vm.runInContext("state.weather=[{time:state.games[0].startsAt,temperature:19.4,code:3}];render()",context);
 assert.ok(app.innerHTML.includes('☁️ 19°'));
 vm.runInContext("state.weather=[{time:state.games[0].startsAt,temperature:17.4,code:61}];render()",context);
 assert.ok(app.innerHTML.includes('🌧️ 17°'));
 assert.ok(app.innerHTML.includes('home-section')&&app.innerHTML.includes('home-rating'));
 assert.ok(app.innerHTML.includes('ИГРА')&&app.innerHTML.includes('Тренер - Анастасия')&&app.innerHTML.includes('Сплит · 2 человека · ★ 5.00 · стаж 7 лет'));
 assert.ok(app.innerHTML.includes('360° Падел'));
 assert.ok(!vm.runInContext('compactGameCard(state.games[0])',context).includes('ПАРНАЯ'));
 assert.ok(vm.runInContext('gameCard(state.games[1])',context).includes('ПАРНАЯ'));
 assert.ok(vm.runInContext('gameDetail(state.games[1])',context).includes('ПАРНАЯ'));
 assert.ok(app.innerHTML.includes('2 места свободно'));
 assert.ok(!app.innerHTML.includes('class="filters"'));
 vm.runInContext("state.filter='tennis';render()",context);
 assert.ok(app.innerHTML.includes('360° Падел'));
 vm.runInContext("state.filter='all';render()",context);
 vm.runInContext("state.games[0].members.push({id:'demo-filled',name:'Игрок'});state.trainings[0].members.push({id:'a',name:'A'},{id:'b',name:'B'});render()",context);
 assert.ok(!app.innerHTML.includes('compact-training')&&!app.innerHTML.includes('Стадион «Динамо»'));
 vm.runInContext("state.games[0].members.pop();state.trainings[0].members=[];render()",context);
 assert.ok(app.innerHTML.includes('Играть</button>'));
 vm.runInContext("state.tab='play';state.playView='games';render()",context);
 assert.ok(app.innerHTML.includes('class="play-title">Играть')&&app.innerHTML.includes('data-play-view="games"')&&app.innerHTML.includes('Найти игру'));
 assert.ok(app.innerHTML.includes('data-locate')&&app.innerHTML.includes('© OpenStreetMap'));
 vm.runInContext("state.catalog.courts.find(c=>c.id==='dinamo').latitude=45;state.catalog.courts.find(c=>c.id==='dinamo').longitude=39;state.location={latitude:45,longitude:39};render()",context);
 assert.ok(app.innerHTML.includes('Рядом · 0.0 км'));
 assert.ok(vm.runInContext("(state.location.latitude=45.06,distanceBadge('dinamo'))",context).includes('Близко'));
 assert.ok(vm.runInContext("(state.location.latitude=45.11,distanceBadge('dinamo'))",context).includes('Далеко'));
 vm.runInContext('state.location=null;render()',context);
 assert.ok(app.innerHTML.includes('data-play-view="tournaments"')&&app.innerHTML.includes('data-play-view="camps"'));
 vm.runInContext("state.playView='tournaments';render()",context);assert.ok(app.innerHTML.includes('Раздел находится в разработке'));
 vm.runInContext("state.playView='camps';render()",context);assert.ok(app.innerHTML.includes('Раздел находится в разработке'));
 vm.runInContext("state.playView='games';render()",context);
 await handlers.click[0]({target:{closest:()=>({dataset:{playView:'training'}})}});
 assert.ok(app.innerHTML.includes('data-play-view="training"')&&app.innerHTML.includes('Тренировки тренеров и заявки игроков.'));
 vm.runInContext("state.tab='home';state.playView='games';render()",context);
 assert.ok(app.innerHTML.includes('Сообщество')&&app.innerHTML.includes('data-tab="community"')&&app.innerHTML.includes('id="chat-badge"'));
 const nav=app.innerHTML.match(/<nav class="nav"[^>]*>([\s\S]*?)<\/nav>/)?.[1];
 assert.ok(nav);assert.deepEqual([...nav.matchAll(/data-tab="([^"]+)"/g)].map(m=>m[1]),['home','play','chat','profile']);
 assert.ok(nav.includes('>Чат')&&nav.includes('<circle cx="12" cy="12" r="9"'));
 assert.ok(nav.includes('tennis-ball-yellow')&&nav.includes('#e5f641'));
 assert.ok(!app.innerHTML.includes('data-back'));
 assert.ok(app.innerHTML.includes('class="brand-logo"><img src="data:image/webp;base64,'));
 vm.runInContext("state.tab='games'; render()",context);assert.match(app.innerHTML,/Найти игру/);
 assert.ok(app.innerHTML.includes('aria-label="Создать игру: выберите корт')&&app.innerHTML.includes('class="info-tip-text">Создать игру'));
 vm.runInContext("state.tab='training';state.me.role='player';render()",context);
 assert.ok(app.innerHTML.includes('<h1 class="page-title">Тренировки</h1>')&&!app.innerHTML.includes('Создать тренировку')&&app.innerHTML.includes('Ищу тренировку'));
 assert.ok(app.innerHTML.includes('class="info-tip-text">Создаёт заявку')&&!app.innerHTML.includes('${infoTip('));
 vm.runInContext("state.form='create-training-request';render()",context);
 assert.ok(app.innerHTML.includes('id="player-training-request-form"')&&app.innerHTML.includes('name="timeFrom"')&&app.innerHTML.includes('name="timeTo"')&&app.innerHTML.includes('name="courtIds"')&&app.innerHTML.includes('id="request-group-seats"'));
 assert.ok(app.innerHTML.includes('min="'+vm.runInContext('nextStartDate()',context)+'"'));
 vm.runInContext("state.form='';render()",context);
 await vm.runInContext("api('/training-requests','POST',{sport:'tennis',format:'split',courtIds:['dinamo','alfa-tennis'],startsAt:new Date(Date.now()+86400000).toISOString(),endsAt:new Date(Date.now()+93600000).toISOString(),note:'Хочу сплит'}).then(()=>refresh()).then(render)",context);
 assert.ok(app.innerHTML.includes('Заявки игроков')&&app.innerHTML.includes('ИЩУ ТРЕНИРОВКУ'));
 assert.ok(app.innerHTML.includes('1/2 участников · свободно 1'));
 vm.runInContext("state.trainingRequestDetail=state.trainingRequests[0];render()",context);
 assert.ok(app.innerHTML.includes('Хочу сплит')&&app.innerHTML.includes('Отменить заявку'));
 vm.runInContext("state.me.id='demo-other-player';state.trainingRequestDetail.joined=false;render()",context);
 assert.ok(app.innerHTML.includes('Участники · 1/2')&&app.innerHTML.includes('data-request-membership="join"'));
 vm.runInContext("state.me.id=demoId;render()",context);
 vm.runInContext("state.me.role='coach';state.me.id='demo-coach-new';state.me.coachSports=['tennis'];state.me.isAdmin=false;render()",context);
 assert.ok(app.innerHTML.includes('id="accept-training-request-form"')&&app.innerHTML.includes('Принять и создать тренировку'));
 vm.runInContext("state.trainingRequestDetail=null;state.tab='play';state.playView='training';render()",context);
 assert.ok(app.innerHTML.includes('data-coach-view="calendar"')&&app.innerHTML.includes('Мой календарь'));
 assert.ok(!app.innerHTML.includes('ИЩУ ТРЕНИРОВКУ'));
 vm.runInContext("state.coachTrainingView='requests';render()",context);
 assert.ok(app.innerHTML.includes('ИЩУ ТРЕНИРОВКУ')&&!app.innerHTML.includes('training-calendar-grid'));
 vm.runInContext("state.me.role='player';state.me.id=demoId;state.me.coachSports=['tennis','padel'];state.trainingRequestDetail=null;state.form='create';render()",context);
 assert.ok(app.innerHTML.includes('после игры участникам придёт уведомление')&&app.innerHTML.includes('подтверждать список участников'));
 assert.ok(app.innerHTML.includes('администратор корта подтвердил вашу запись'));
 vm.runInContext("state.trainingRequestDetail=null;state.form='';render()",context);
 vm.runInContext("state.tab='community';state.communityTab='people';state.people=[{id:'demo-host',name:'Алексей',role:'player',city:'Краснодар',avatarId:'male-cap'}];render()",context);
 assert.ok(app.innerHTML.includes('data-direct="demo-host"')&&app.innerHTML.includes('data-user="demo-host"'));
 assert.ok(app.innerHTML.includes('data-community="rating"')&&app.innerHTML.includes('data-community="events"')&&app.innerHTML.includes('data-community="resources"'));
 assert.ok(!app.innerHTML.includes('data-community="chats"'));
 vm.runInContext("state.communityTab='resources';render()",context);assert.ok(app.innerHTML.includes('Федерация тенниса России')&&app.innerHTML.includes('target="_blank"'));
 vm.runInContext("state.communityTab='events';render()",context);assert.ok(app.innerHTML.includes('Мероприятия')&&app.innerHTML.includes('Игровой марафон')&&app.innerHTML.includes('туба теннисных мячей'));
 vm.runInContext("state.communityTab='rating';render()",context);assert.ok(app.innerHTML.includes('Пока нет рейтинговых матчей'));
 vm.runInContext("state.tab='chat';state.unread=2;state.inbox=[{key:'direct:demo-host',peerName:'Алексей',title:'Личный чат',lastMessage:'Привет',unread:2}];render()",context);
 assert.ok(app.innerHTML.includes('data-inbox-thread="direct:demo-host"')&&app.innerHTML.includes('class="unread-pill">2</b>'));
 vm.runInContext("state.tab='games';render()",context);
 assert.ok(app.innerHTML.includes('Игроки и корты рядом с вами.')&&!app.innerHTML.includes('Игроки и корты Краснодара'));
 vm.runInContext("state.form='create';render()",context);
 assert.ok(app.innerHTML.includes('name="friendsOnly"')&&app.innerHTML.includes('name="repeat"'));
 assert.equal(vm.runInContext("repeatLabel('2026-10-06')",context),'Повторять каждый вторник · 30 дней');
 vm.runInContext("state.config.botUsername='TennisGOgo_bot'",context);
 assert.equal(vm.runInContext("listingLink('training','sample-id')",context),'https://t.me/TennisGOgo_bot?startapp=training_sample-id');
 vm.runInContext("state.form='';render()",context);
 vm.runInContext("state.userProfile={id:'demo-host',name:'Алексей И.',role:'player',city:'Краснодар',gender:'male',playingYears:2,ntrpLevel:3,ratings:{tennis:{rating:1500}},online:false,friendStatus:null,media:[]};render()",context);
 assert.ok(app.innerHTML.includes('В друзья')&&app.innerHTML.includes('Не в сети')&&app.innerHTML.includes('public-stats')&&!app.innerHTML.includes('tel:'));
 vm.runInContext('state.userProfile=null;render()',context);
 const restored={open:false,querySelector:()=>restoredList},restoredList={scrollTop:0};
 app.querySelectorAll=()=>[{dataset:{courtMenu:'game'},querySelector:()=>({scrollTop:73})}];
 app.querySelector=selector=>selector.includes('game')?restored:null;
 vm.runInContext('render()',context);
 assert.equal(restored.open,true);assert.equal(restoredList.scrollTop,73);
 delete app.querySelectorAll;delete app.querySelector;
 assert.ok(app.innerHTML.includes('data-direct="demo-host"')&&app.innerHTML.includes('data-user="demo-host"')&&app.innerHTML.includes('data-game="'));
 context.gameId=vm.runInContext('state.games[0].id',context);
 await handlers.click[0]({target:{closest:()=>({dataset:{direct:'demo-host',name:'Алексей'},hasAttribute:()=>false})}});
 assert.equal(vm.runInContext('state.chat.kind',context),'direct');
 vm.runInContext('back()',context);
 await handlers.click[0]({target:{closest:()=>({dataset:{game:context.gameId},hasAttribute:()=>false})}});
 assert.equal(vm.runInContext('state.detail.id',context),context.gameId);
 assert.ok(app.innerHTML.includes('detail-organizer')&&app.innerHTML.includes('data-user="demo-host"')&&app.innerHTML.includes('Написать организатору'));
 vm.runInContext('back()',context);
 vm.runInContext("state.form='create'; render()",context);assert.ok(app.innerHTML.includes('id="create-form"'));assert.ok(app.innerHTML.includes('4 игрока · парная'));assert.ok(app.innerHTML.includes('Спортивная академия «Вопреки» · Крытые + открытые — ул. Невкипелого, 24/4'));assert.ok(app.innerHTML.includes('Что означают уровни NTRP 1.0–7.0?'));assert.ok(app.innerHTML.includes('Ракетка для падела'));assert.ok(app.innerHTML.includes('Кто может присоединиться'));
 assert.ok(app.innerHTML.includes('На рейтинг')&&app.innerHTML.includes('name="requiresApproval"'));
 vm.runInContext("state.form='edit-profile'; render()",context);assert.ok(app.innerHTML.includes('id="profile-form"'));assert.ok(app.innerHTML.includes('Своя фотография'));assert.ok(app.innerHTML.includes('Уровень тенниса · NTRP'));
 assert.ok(app.innerHTML.includes('name="city"')&&app.innerHTML.includes('name="phone"'));
 vm.runInContext("state.form='';state.tab='profile';state.me.role='coach';render()",context);
 assert.ok(app.innerHTML.includes('Создать тренировку'));
 assert.ok(!app.innerHTML.includes('Уровень тенниса · NTRP'));
 vm.runInContext("state.me.role='player';state.me.ratings={tennis:{rating:1584,matches:4,wins:3,losses:1},padel:{rating:1500,matches:0,wins:0,losses:0}};render()",context);
 assert.ok(!app.innerHTML.includes('1584'));vm.runInContext("state.form='my-rating';render()",context);
 assert.ok(app.innerHTML.includes('Tennis GO')&&app.innerHTML.includes('1584')&&app.innerHTML.includes('Предварительный'));vm.runInContext("state.form='';render()",context);
 vm.runInContext("state.me.role='coach';state.tab='home';render()",context);
 assert.ok(app.innerHTML.includes('Тренера')&&!app.innerHTML.includes('class="primary training-action"'));
 vm.runInContext("state.form='create-training';render()",context);
 assert.ok(app.innerHTML.includes('id="training-form"')&&app.innerHTML.includes('Сплит · 2 человека')&&app.innerHTML.includes('NTRP от')&&app.innerHTML.includes('NTRP до'));
 assert.ok(app.innerHTML.includes('<option value="padel">Падел</option>')&&app.innerHTML.includes('Динамо-Кубань'));
 vm.runInContext("state.me.coachSports=['padel'];render()",context);
 assert.ok(app.innerHTML.includes('<option value="padel">Падел</option>')&&!app.innerHTML.includes('<option value="tennis">🎾 Теннис</option>'));
 assert.ok(app.innerHTML.includes('360° Падел · Крытый — ул. Тополиная, 33А'));
 vm.runInContext("state.me.coachSports=['tennis','padel'];render()",context);
 assert.ok(!app.innerHTML.includes('360° Падел · Крытый — ул. Тополиная, 33А'));
 const courtSelect={innerHTML:''},trainingForm={elements:{courtId:courtSelect}};
 context.trainingSport={name:'sport',value:'padel',form:trainingForm,closest:()=>trainingForm};
 for(const handler of handlers.change)await handler({target:context.trainingSport});
 assert.match(courtSelect.innerHTML,/360° Падел · Крытый — ул. Тополиная, 33А/);
 assert.ok(app.innerHTML.includes('data-back'));
 vm.runInContext("state.me.role='player';state.form='';render()",context);
 vm.runInContext("state.tab='training';render()",context);
 assert.ok(app.innerHTML.includes('>Тренировки</h1>')&&app.innerHTML.includes('training-gender-filter')&&app.innerHTML.includes('training-format-filter'));
 assert.ok(app.innerHTML.includes('training-calendar-coach-avatar avatar" data-user="demo-coach"'));
 assert.ok(app.innerHTML.includes('format-split')&&app.innerHTML.includes('0/2 записано'));
 assert.ok(app.innerHTML.includes('training-sport-filter')&&app.innerHTML.includes('Теннис и падел'));
 vm.runInContext("state.trainingSport='padel';render()",context);assert.ok(app.innerHTML.includes('Тренировок на этот период нет'));
 vm.runInContext("state.trainingSport='tennis';render()",context);assert.ok(app.innerHTML.includes('1 тренировка'));
 vm.runInContext("state.trainingSport='all';render()",context);
 assert.ok(app.innerHTML.includes('data-training-court="dinamo"')&&app.innerHTML.includes('data-training-court="padel360"'));
 assert.ok(!app.innerHTML.includes('booking-form')&&!app.innerHTML.includes('Индивидуальная заявка'));
 vm.runInContext("state.trainingGender='male';render()",context);assert.ok(app.innerHTML.includes('Тренировок на этот период нет'));
 vm.runInContext("state.trainingGender='all';state.trainingCourts=['padel360'];render()",context);assert.ok(app.innerHTML.includes('Тренировок на этот период нет'));
 vm.runInContext("state.trainingCourts=['padel360','dinamo'];render()",context);assert.ok(app.innerHTML.includes('1 тренировка'));
 vm.runInContext("state.trainingFormat='individual';render()",context);assert.ok(app.innerHTML.includes('Тренировок на этот период нет'));
 vm.runInContext("state.trainingFormat='all';state.trainingGender='all';state.trainingCourts=[];state.trainings[0].members.push({id:'demo-host',name:'Алексей',avatarId:'male-cap'});render()",context);
 assert.ok(app.innerHTML.includes('1/2 записано'));
 vm.runInContext('openTraining(state.trainings[0].id)',context);
 assert.ok(app.innerHTML.includes('Записались · 1/2')&&app.innerHTML.includes('data-user="demo-host"'));
 vm.runInContext('state.trainings[0].coachId=state.me.id;render()',context);
 assert.ok(app.innerHTML.includes('data-edit="training:')&&app.innerHTML.includes('Отменить объявление'));
 vm.runInContext("state.editTarget={kind:'training',id:state.trainings[0].id};state.trainingDetail=null;state.form='edit-training';render()",context);
 assert.ok(app.innerHTML.includes('id="edit-training-form"')&&app.innerHTML.includes('Сплит'));
 vm.runInContext("state.form='';state.editTarget=null;state.trainings[0].coachId='demo-coach';state.trainingDetail=state.trainings[0];render()",context);
 await vm.runInContext("openUser('demo-host')",context);
 assert.ok(app.innerHTML.includes('АНКЕТА ИГРОКА')&&app.innerHTML.includes('Алексей')&&app.innerHTML.includes('✉ Написать'));
 vm.runInContext('back()',context);await vm.runInContext("openDirect('demo-host','Алексей')",context);
 assert.ok(app.innerHTML.includes('chat-peer-profile')&&app.innerHTML.includes('data-user="demo-host"'));
 await vm.runInContext("openUser('demo-host')",context);assert.ok(app.innerHTML.includes('АНКЕТА ИГРОКА'));
 vm.runInContext('back()',context);assert.ok(app.innerHTML.includes('chat-peer-profile'));
 vm.runInContext('back()',context);assert.ok(app.innerHTML.includes('Записались · 1/2'));
 vm.runInContext('back()',context);assert.ok(app.innerHTML.includes('>Тренировки</h1>'));
 vm.runInContext('openGame(state.games[0].id)',context);assert.ok(app.innerHTML.includes('data-user="demo-host"'));
 await vm.runInContext("openChat('game',state.games[0].id)",context);
 assert.ok(app.innerHTML.includes('id="chat-form"')&&app.innerHTML.includes('Обновить сообщения'));
 await vm.runInContext("api('/chats/game/'+state.games[0].id+'/demo-host','POST',{message:'Здравствуйте!'}).then(()=>refreshChat())",context);
 assert.ok(app.innerHTML.includes('Здравствуйте!'));
 vm.runInContext('back()',context);assert.ok(app.innerHTML.includes('Участники'));
 vm.runInContext('state.games[0].creatorId=state.me.id;render()',context);
 assert.ok(app.innerHTML.includes('Редактировать')&&app.innerHTML.includes('Отменить объявление'));
 vm.runInContext("state.editTarget={kind:'game',id:state.games[0].id};state.detail=null;state.form='edit-game';render()",context);
 assert.ok(app.innerHTML.includes('id="edit-game-form"')&&app.innerHTML.includes('Сохранить изменения'));
 vm.runInContext("state.form='';state.editTarget=null;state.games[0].creatorId='demo-host';state.detail=state.games[0];render()",context);
 vm.runInContext('back()',context);
 vm.runInContext("state.tab='home';state.history=[];pushView();state.tab='training';render();back()",context);
 assert.ok(app.innerHTML.includes('Подойдут вам'));
 const boxes={'#level-guide-items':{innerHTML:''},'#court-address':{textContent:''},'#level-summary':{innerHTML:''}};
 const form={elements:{sport:{value:'padel'},seats:{value:'2'},courtId:{value:'padel360',innerHTML:''},levelMin:{value:'2.5',innerHTML:''},levelMax:{value:'3.5',innerHTML:''}},querySelector:q=>boxes[q]};
 context.fakeForm=form;vm.runInContext('updateCreateChoices(fakeForm)',context);
 assert.equal(form.elements.seats.value,'4');
 assert.match(form.elements.courtId.innerHTML,/360° Падел · Крытый — ул. Тополиная, 33А/);
 assert.doesNotMatch(form.elements.courtId.innerHTML,/Динамо-Кубань/);
 assert.match(boxes['#level-guide-items'].innerHTML,/Использую стены/);
 form.elements.rating={checked:true};vm.runInContext('syncGameFormat(fakeForm)',context);
 assert.equal(form.elements.seats.value,'4');
 assert.ok(vm.runInContext("createPage()",context).includes('name="rating"'));
 assert.ok(!vm.runInContext("createPage()",context).includes('name="kind"'));
 vm.runInContext("state.form='';state.tab='games';state.filter='all';state.when='all';state.courts=['dinamo','padel360'];state.availableOnly=true;render()",context);
 assert.ok(app.innerHTML.includes('Пол игроков')&&app.innerHTML.includes('data-rating-only'));
 assert.ok(app.innerHTML.includes('<option value="Ростов-на-Дону"')&&app.innerHTML.includes('<option value="Элиста"'));
 assert.equal(vm.runInContext('visibleGames({advanced:true}).length',context),2);
 assert.ok(app.innerHTML.includes('Корты · выбрано 2'));
 const summary={textContent:''};
 for(const handler of handlers.change)await handler({target:{dataset:{gameCourt:'padel360'},checked:false,closest:()=>({querySelector:()=>summary})}});
 assert.equal(vm.runInContext('state.courts.length',context),1);
 assert.equal(summary.textContent,'Корты · выбрано 1');
 vm.runInContext("state.courts=['dinamo'];render()",context);
 assert.equal(vm.runInContext('visibleGames({advanced:true}).length',context),1);
 assert.ok(app.innerHTML.includes('1 найдено'));
 assert.match(app.innerHTML,/Стадион «Динамо»/);
 assert.doesNotMatch(app.innerHTML,/<h3 class="game-title">360° Падел/);
 vm.runInContext("state.genderFilter='female';render()",context);assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.genderFilter='male';render()",context);assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.genderFilter='all';state.ratingOnly=true;render()",context);assert.ok(app.innerHTML.includes('0 найдено'));
 vm.runInContext("state.games[0].kind='rating';render()",context);assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.ratingOnly=false;state.games[0].kind='friendly';render()",context);
 const upcoming=vm.runInContext('state.games[0].startsAt',context);
 vm.runInContext("state.games[0].startsAt=new Date(Date.now()-60000).toISOString();render()",context);
 assert.equal(vm.runInContext('visibleGames({advanced:true}).length',context),0);
 context.upcoming=upcoming;vm.runInContext('state.games[0].startsAt=upcoming;render()',context);
 vm.runInContext("state.games[0].creatorRole='player';state.games[0].creatorNtrp=3.0;state.myLevelOnly=true;render()",context);
 assert.ok(app.innerHTML.includes('1 найдено'));
 vm.runInContext("state.games[0].creatorNtrp=5.0;render()",context);
 assert.ok(app.innerHTML.includes('0 найдено'));
 context.FileReader=class{readAsDataURL(){this.result='data:image/png;base64,AAAA';queueMicrotask(()=>this.onload());}};
 context.Image=class{set src(value){this.naturalWidth=800;this.naturalHeight=600;queueMicrotask(()=>this.onload());}};
 context.document.createElement=()=>({getContext:()=>({drawImage(){}}),toDataURL:()=>"data:image/jpeg;base64,/9j/2Q=="});
 const jpeg=await vm.runInContext("imageData({type:'image/png',size:100})",context);
 assert.equal(jpeg,'data:image/jpeg;base64,/9j/2Q==');
 vm.runInContext("state.pendingVotes=[{id:'vote-test',seats:2,startsAt:new Date().toISOString(),venue:'Динамо',members:[{id:state.me.id,name:state.me.name,team:'A'},{id:'other',name:'Вика',team:'B'}]}];state.form='';render()",context);
 assert.ok(app.innerHTML.includes('role="dialog"')&&app.innerHTML.includes('data-vote-choice="win"')&&app.innerHTML.includes('Мы не играли на счёт'));
 vm.runInContext("state.pendingVotes=[];render()",context);
 assert.ok(!app.innerHTML.includes('role="dialog"'));
 vm.runInContext("state.me.role='club';state.me.club={name:'Теннис Парк',city:'Ростов-на-Дону',address:'ул. Тестовая, 12',phone:'+7 900 123-45-67',sports:['tennis'],status:'approved'};state.form='';state.clubDate='2026-09-28';state.clubCalendar=[{startsAt:'2026-09-28T15:00:00Z',duration:90,sport:'tennis',guestName:'Вика'}];render()",context);
 assert.ok(app.innerHTML.includes('Календарь клуба')&&app.innerHTML.includes('Забронировал: Вика'));
 assert.ok(!app.innerHTML.includes('class="nav"'));
});

test('desktop browser shows an actionable Telegram entry instead of a blank screen',async()=>{
 const dir=path.dirname(fileURLToPath(import.meta.url));
 const source=fs.readFileSync(path.join(dir,'../public/app.js'),'utf8');
 const app={innerHTML:'',addEventListener(){}};
 const fetch=async url=>({ok:!url.includes('/me'),json:async()=>url.includes('/config')?{botUsername:'TennisGOgo_bot',cities:['Краснодар']}:{error:'Откройте приложение через Telegram'}});
 const context={window:{},document:{querySelector:q=>q==='#app'?app:null},localStorage:{getItem:()=>null,setItem(){}},crypto,Intl,Date,URLSearchParams,location:{search:''},navigator:{},fetch,setTimeout,console};
 vm.createContext(context);vm.runInContext(source,context);await new Promise(resolve=>setTimeout(resolve,20));
 assert.ok(app.innerHTML.includes('Открыть бота в Telegram')&&app.innerHTML.includes('https://t.me/TennisGOgo_bot')&&app.innerHTML.includes('кнопку «Меню»'));
});
