import crypto from 'node:crypto';
import {rangeFor,dateKey} from './public/club-time.js';
export function createClubs({db,fail,notifyUser,isAdmin,audit,now}){
 const add=(table,cols)=>{const existing=new Set(db.prepare(`PRAGMA table_info(${table})`).all().map(c=>c.name));for(const [name,type] of cols)if(!existing.has(name))db.exec(`ALTER TABLE ${table} ADD COLUMN ${name} ${type}`);};
 add('clubs',[['court_type','TEXT'],['photos_json',"TEXT NOT NULL DEFAULT '[]'"]]);
 add('court_reservations',[['status',"TEXT NOT NULL DEFAULT 'confirmed'"],['source',"TEXT NOT NULL DEFAULT 'app'"],['guest_name','TEXT'],['guest_phone','TEXT'],['note',"TEXT NOT NULL DEFAULT ''"],['resolved_at','TEXT'],['resolved_by','TEXT']]);
 db.exec("UPDATE clubs SET photos_json=json_array(photo_data) WHERE photos_json='[]' AND photo_data IS NOT NULL; UPDATE court_reservations SET status='cancelled' WHERE cancelled_at IS NOT NULL;");
 db.exec('CREATE INDEX IF NOT EXISTS court_booking_state ON court_reservations(club_id,status,starts_at)');
 const raw=id=>db.prepare('SELECT * FROM clubs WHERE owner_id=?').get(id);
 const dto=c=>c?{ownerId:c.owner_id,name:c.name,address:c.address,city:c.city,phone:c.phone,sports:JSON.parse(c.sports),status:c.status,photoData:c.photo_data,photos:JSON.parse(c.photos_json||'[]'),courtType:c.court_type,surface:c.surface,opensAt:c.opens_at,closesAt:c.closes_at,hourlyPrice:c.hourly_price}:null;
 function extras(b,previous){
  const courtType=b.courtType??previous?.court_type;
  if(!['outdoor','indoor'].includes(courtType))fail(400,'Выберите тип корта: открытый или закрытый');
  const photos=b.clubPhotos??(b.clubPhotoData?[b.clubPhotoData]:previous?JSON.parse(previous.photos_json||'[]'):[]);
  if(!Array.isArray(photos)||!photos.length||photos.length>6)fail(400,'Добавьте от 1 до 6 фотографий');
  for(const photo of photos){if(typeof photo!=='string'||photo.length>350000||!/^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/.test(photo))fail(400,'Фотографии должны быть JPEG до 250 КБ');const bytes=Buffer.from(photo.slice(23),'base64');if(bytes.length<4||bytes.length>250000||bytes[0]!==255||bytes[1]!==216||bytes.at(-2)!==255||bytes.at(-1)!==217)fail(400,'Некорректное фото JPEG');}
  return {courtType,photos};
 }
 function saveExtras(id,e){db.prepare('UPDATE clubs SET court_type=?,photos_json=?,photo_data=? WHERE owner_id=?').run(e.courtType,JSON.stringify(e.photos),e.photos[0],id);}
 function manage(me,id){const c=raw(id);if(!c)fail(404,'Клуб не найден');if(me.id!==id&&!isAdmin(me.id))fail(403,'Доступно только владельцу клуба или администратору приложения');return c;}
 const select=`SELECT r.id,r.club_id AS clubId,r.user_id AS userId,r.sport,r.starts_at AS startsAt,r.duration,r.status,r.source,COALESCE(r.guest_name,NULLIF(u.display_name,''),u.name) AS guestName,COALESCE(r.guest_phone,u.phone,'') AS guestPhone,r.note,r.cancelled_at AS cancelledAt FROM court_reservations r JOIN users u ON u.id=r.user_id`;
 const rows=(id,range)=>db.prepare(select+' WHERE r.club_id=? AND r.starts_at<? AND datetime(r.starts_at,\'+\'||r.duration||\' minutes\')>datetime(?) ORDER BY r.starts_at').all(id,range.end,range.start);
 function calendar(me,id,date,view){const c=manage(me,id);let range;try{range=rangeFor(date||dateKey(Date.now()),view||'day');}catch{fail(400,'Проверьте дату и период');}return {club:dto(c),...range,reservations:rows(id,range),pending:db.prepare(select+" WHERE r.club_id=? AND r.status='pending' AND r.cancelled_at IS NULL AND r.starts_at>? ORDER BY r.starts_at").all(id,now())};}
 function conflict(id,start,duration,ignore=''){return db.prepare("SELECT id FROM court_reservations WHERE club_id=? AND id<>? AND status='confirmed' AND cancelled_at IS NULL AND starts_at<? AND datetime(starts_at,'+'||duration||' minutes')>datetime(?) LIMIT 1").get(id,ignore,new Date(Date.parse(start)+duration*60000).toISOString(),start);}
 function checkTime(c,b){const n=Date.parse(b.startsAt),duration=Number(b.duration);if(!Number.isFinite(n)||n<Date.now()||n>Date.now()+90*86400000||!Number.isInteger(duration)||duration<30||duration>720||duration%30)fail(400,'Выберите будущее время до 90 дней и длительность от 30 минут с шагом 30 минут');const start=new Date(n).toISOString(),end=n+duration*60000,day=dateKey(n),open=Date.parse(day+'T'+c.opens_at+':00+03:00'),close=Date.parse(day+'T'+c.closes_at+':00+03:00');if(n<open||end>close)fail(400,'Запись должна быть в пределах часов работы клуба');if(!JSON.parse(c.sports).includes(b.sport))fail(400,'Этот вид спорта недоступен в клубе');return {start,duration};}
 const phoneOK=s=>typeof s==='string'&&/^[+\d()\-\s]+$/.test(s)&&s.replace(/\D/g,'').length>=10&&s.replace(/\D/g,'').length<=15;
 function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const out=fn();db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}
 function expireOverlaps(id,start,duration,except){const pending=db.prepare(select+" WHERE r.club_id=? AND r.id<>? AND r.status='pending' AND r.starts_at<? AND datetime(r.starts_at,'+'||r.duration||' minutes')>datetime(?)").all(id,except,new Date(Date.parse(start)+duration*60000).toISOString(),start);for(const r of pending){db.prepare("UPDATE court_reservations SET status='rejected',resolved_at=? WHERE id=?").run(now(),r.id);notifyUser(r.userId,'Заявка отклонена: время уже занято. Выберите другой слот.','courtbookings');}}
 function create(me,id,b,manual=false){const c=manual?manage(me,id):raw(id);if(!c||c.status!=='approved')fail(409,'Клуб пока не принимает записи');if(!me.registered)fail(403,'Сначала завершите регистрацию');const {start,duration}=checkTime(c,b);const guestName=String(b.guestName||me.name||'').trim(),guestPhone=String(b.guestPhone||me.phone||'').trim(),note=String(b.note||'').trim();if(!guestName||guestName.length>80||!phoneOK(guestPhone)||note.length>300)fail(400,'Укажите имя клиента, телефон и комментарий до 300 символов');return transaction(()=>{if(conflict(id,start,duration))fail(409,'Это время уже забронировано. Выберите другой слот');if(!manual&&db.prepare("SELECT id FROM court_reservations WHERE club_id=? AND user_id=? AND starts_at=? AND status='pending'").get(id,me.id,start))fail(409,'Вы уже отправили заявку на это время');const booking={id:crypto.randomUUID(),clubId:id,startsAt:start,duration,sport:b.sport,status:manual?'confirmed':'pending',source:manual?'admin':'app',guestName,guestPhone,note};db.prepare('INSERT INTO court_reservations(id,club_id,user_id,sport,starts_at,duration,created_at,status,source,guest_name,guest_phone,note,resolved_at,resolved_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(booking.id,id,me.id,b.sport,start,duration,now(),booking.status,booking.source,guestName,guestPhone,note,manual?now():null,manual?me.id:null);if(manual){expireOverlaps(id,start,duration,booking.id);audit(me.id,'manual-booking','club',id,booking.id);}else{const when=new Date(start).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hour12:false});notifyUser(id,`Новая заявка · ${c.name} · ${when} · ${duration} мин · ${guestName}. Подтвердите запись в календаре.`,`clubbooking_${booking.id}`);notifyUser(me.id,`Заявка в «${c.name}» отправлена. Дождитесь подтверждения клуба.`,'courtbookings');}return booking;});}
 function decision(me,id,bookingId,action){const c=manage(me,id);if(!['confirm','reject','cancel'].includes(action))fail(400,'Неизвестное действие');return transaction(()=>{const r=db.prepare(select+' WHERE r.id=? AND r.club_id=?').get(bookingId,id);if(!r)fail(404,'Запись не найдена');const target={confirm:'confirmed',reject:'rejected',cancel:'cancelled'}[action];if(r.status===target)return {ok:true};if(action==='cancel'?!['pending','confirmed'].includes(r.status):r.status!=='pending')fail(409,'Статус записи уже изменился');if(action==='confirm'){if(c.status!=='approved')fail(409,'Клуб ещё не подтверждён');checkTime(c,r);if(conflict(id,r.startsAt,r.duration,r.id))fail(409,'Слот уже занят');}db.prepare('UPDATE court_reservations SET status=?,cancelled_at=?,resolved_at=?,resolved_by=? WHERE id=?').run(target,action==='cancel'?now():null,now(),me.id,r.id);if(action==='confirm')expireOverlaps(id,r.startsAt,r.duration,r.id);if(r.source==='app')notifyUser(r.userId,`${action==='confirm'?'Бронирование подтверждено':action==='reject'?'Заявка отклонена':'Бронирование отменено'} · ${c.name} · ${new Date(r.startsAt).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',hour12:false})}`,'courtbookings');audit(me.id,action+'-booking','club',id,r.id);return {ok:true};});}
 function availability(id,date){const c=raw(id);if(!c||c.status!=='approved')fail(404,'Клуб недоступен');let range;try{range=rangeFor(date);}catch{fail(400,'Укажите дату');}return {club:dto(c),date,busy:rows(id,range).filter(r=>r.status==='confirmed'&&!r.cancelledAt).map(({startsAt,duration})=>({startsAt,duration}))};}
 return {raw,dto,extras,saveExtras,calendar,create,decision,availability};
}
